### ISSUE TITLE
Latencies when Redis server is down

### ISSUE THREAD

**Issue by fabienrousseau** [redisson/redisson#1010]
Hi,

During our tests of redisson, we noticed that if the redis server is down, the latency is around 100ms, no matter what.
This is problematic for our use case because it slows down too much and we would prefer a fast response/error.
After carefully reading configuration options and experimenting with many tests, we could not find a solution.
Do you have an idea of what could provoke this latency ?

Below is a simplified code allowing to reproduce it (no need to launch a redis instance):

```java
package test;

import org.redisson.Redisson;
import org.redisson.api.RBucket;
import org.redisson.api.RedissonClient;
import org.redisson.client.codec.StringCodec;
import org.redisson.config.Config;
import org.redisson.config.SingleServerConfig;

public class RedisDownTest {

    public static void main(String[] args) {
        Config config = new Config();
        config.setCodec(StringCodec.INSTANCE);
        SingleServerConfig singleServerConfig = config.useSingleServer();
        singleServerConfig.setAddress("redis://localhost:6378"); // 6378 is on purpose, there is no redis listening on it
        singleServerConfig.setConnectionMinimumIdleSize(0); // this was set to 0 just to be able to build the client without error
        singleServerConfig.setSubscriptionConnectionMinimumIdleSize(0);
        singleServerConfig.setSubscriptionConnectionPoolSize(0);
        singleServerConfig.setConnectTimeout(50);
        singleServerConfig.setTimeout(50);
        singleServerConfig.setRetryInterval(0);
        singleServerConfig.setRetryAttempts(0);
        singleServerConfig.setReconnectionTimeout(0);
        singleServerConfig.setPingTimeout(0);
        config.setRedissonReferenceEnabled(false);
        RedissonClient redissonClient = Redisson.create(config);

        for (int i = 0 ; i < 20 ; i++) {
            long start = System.currentTimeMillis();
            try {
                RBucket<String> bucket = redissonClient.getBucket("someKey");
                String content = bucket.get();
            } catch (Exception e) {
            } finally {
                long end = System.currentTimeMillis();
                System.out.println("Took: " + (end - start) + "ms");
            }
        }
    }
}
```

Here are the logs for the last 10 iterations:
```
Took: 100ms
Took: 98ms
Took: 102ms
Took: 97ms
Took: 100ms
Took: 101ms
Took: 101ms
Took: 98ms
Took: 102ms
Took: 97ms
```

**Comment by jiminhsieh** [comment]
@fabienrousseau I found [where](https://github.com/redisson/redisson/blob/redisson-3.5.5/redisson/src/main/java/org/redisson/connection/MasterSlaveConnectionManager.java#L243-L252) cause this 100ms latency. Based on your example, you have to set the minimum number of `timeout`, `retryInterval`, or `reconnectionTimeout` bigger than 2.

@mrniko I have some questions about [this range of code](https://github.com/redisson/redisson/blob/redisson-3.5.5/redisson/src/main/java/org/redisson/connection/MasterSlaveConnectionManager.java#L243-L252).
* Should we add `connectTimeout` to [the array of timeouts](https://github.com/redisson/redisson/blob/redisson-3.5.5/redisson/src/main/java/org/redisson/connection/MasterSlaveConnectionManager.java#L243)?
* This issue is caused by picking min timeout. I think it would be better to pick min timeout that bigger than 2. 

BTW, I can help with this ticket. :)

**Comment by fabienrousseau** [comment]
@jiminhsieh Awesome
Thanks for your help and showing the code. I've tested with 2ms for retryInterval & reconnectionTimeout and it works (ie a few ms).

I'll let the ticket open because I think the example above is a legitimate config and code might be changed to support it (but feel free to close it).

**Comment by jiminhsieh** [comment]
@jackygurui Do you have any thought about this ticket? Thanks! :)
