### ISSUE TITLE
Set removeRandom(10)  throws Exception 

### ISSUE THREAD

**Issue by tonychenz** [redisson/redisson#1167]
redission.getSet("key").removeRandom(10);
it seems to use the command "SPOP key 10"
but in fact redis Set doesn't support that uses, SPOP  only pop out one value at a time. So this will cause an Exception "wrong number of arguments for 'spop' command"

i am using redission version 3.5.5;

and i hope redission wilol support the SRANDMEMBER command in the future

**Comment by jackygurui** [comment]
The SPOP command supported this usage since v3.2, please see https://redis.io/commands/spop for more details.

**Comment by tonychenz** [comment]
OMG, I am using a low version of redis. So is there any case I can get random values from the Set with redission not use removeRandom(num);

**Comment by jackygurui** [comment]
Are you trying to get the random values or removing random ones?

If you want to get random values the `random()` method can be used to retrieve **1** random value. Although redis supports retrieving multiple random values since v2.6, redisson has not yet implemented it in the `RSet`. To remove random values without using `removeRandom(int)` method, you will have to either get some random values and then remove it via `remove(E)` or `removeAll(Collection)` method. Alternatively you can write a Lua script to perform the above in an atomic fashion.

**Comment by tonychenz** [comment]
ok I got that
