### ISSUE TITLE
RxJava 2 Support

### ISSUE THREAD

**Issue by Exerosis** [redisson/redisson#1177]
I was hoping to see support for RxJava2, I love having Redis on the stack when I make apps, but it's a real pain when almost every other library has standardized. Thanks for considering :)

**Comment by psakthisivram** [comment]
It would be nice to see migration to rxjava 2.x since rxjava 1.x has officially out of support. Observing the following error when using Reactive operation.

For Ex :
RBucketReactive<String> bucket = redissonReactiveClient.getBucket(key);
RxReactiveStreams.toObsersable(bucket.get());

is complaining that "Cannot access rx.Completable" since I have rxjava 2.x in classpath.

**Comment by mrniko** [comment]
Done
