### ISSUE TITLE
PermitExpirableSemaphore to be able to make expirable permit to a normal permit

### ISSUE THREAD

**Issue by jackygurui** [redisson/redisson#1395]
Once a permit is acquired as an expirable permit, there should be a way to remove the expiry and make it to a normal permit.

**Comment by cherrydev** [comment]
Also I'm looking for a way to extend a permit that's already being held. 

Here's a use-case:

* I need expirable permits because our microservice infrastructure could potentially kill services on occasion and we must ensure that semaphores can't be held indefinitely.
* I need a semaphore instead of any sort of regular Lock because I have async and/or multi-threaded tasks.
* Each task has many items to be processed and needs to hold onto state in between steps in order to efficiently process the items.
* Each task must hold an exclusive mutex on a resource while it processes the items so that corruption can't occur
* There's no way to know how many items will need to be processed (or how long it will take) until the process begins
* If the task gets interrupted in the middle (because its mutex expires) it will have to start over from scratch

So, if I choose a very long expiration time in order to ensure that any potential task can be completed by the end of it I lose most of the safety of using expiring permits. If I choose a short expiration time eventually a task will extend beyond that time. If I attempt to release and re-acquire a permit in the middle of the task I risk losing the permit to another waiter.

I hope this makes sense.  I may attempt to subclass PermitExpirableSemaphore to add a `refresh(String existingPermit)` method that will return a new permitId as long as the existing one is still valid.

**Comment by cherrydev** [comment]
So, I'm looking deeper into this and it looks like this SHOULD work simply by calling `ZADD ${timeoutName} XX CH ${newTimeoutDate} ${permitId}`

This will change the timeout of the permit if the permit exists and return true if it's updated and false if it's not.

It does have the following characteristics, though:
* It will not check to see if the permit already expired, but I don't know if this is important, since the `PermitExpirableSemaphore` is already "unfair".
* It does not check if `newTimeoutDate` is in the past, but neither do the existing methods.

What do you think?

**Comment by mrniko** [comment]
Done. `RPermitExpirableSemaphore.updateLeaseTime` method added

**Comment by jackygurui** [comment]
Thank you @cherrydev for the addition.

Great work! @mrniko
