### ISSUE TITLE
获取所有key时候空指针异常

### ISSUE THREAD

**Issue by wangxlwithall** [redisson/redisson#1598]
我在测试使用redisson.getKeys().getKeys()方法时候发现org.redisson.misc.CompositeIterable.java第63行如下代码报java.lang.NullPointerException，

   public boolean hasNext() {
        if (currentIterator == null || !currentIterator.hasNext()) {
            while (listIterator.hasNext()) {    ---63行
                Iterator<T> iterator = listIterator.next();
                if (iterator.hasNext()) {
                    currentIterator = iterator;
                    return true;
                }
            }
            return false;
        }
        return currentIterator.hasNext();
    }

**Comment by Pepe-Lu** [comment]
I fall into this `NullPointerException` once while I call `hasNext()` of `CompositeIterable<T>` before call `iterator()`. From the source code below we can see the `listIterator` field is initialized in `iterator()`, and used in `hasNext()`. So if you call `hasNext()` before `iterator()`, you will definitely got an `NullPointerException`.

    public class CompositeIterable<T> implements Iterable<T>, Iterator<T> {

    private List<Iterable<T>> iterablesList;
    private Iterable<T>[] iterables;

    private Iterator<Iterator<T>> listIterator;
    private Iterator<T> currentIterator;

    public CompositeIterable(List<Iterable<T>> iterables) {
        this.iterablesList = iterables;
    }

    public CompositeIterable(Iterable<T> ... iterables) {
        this.iterables = iterables;
    }

    public CompositeIterable(CompositeIterable<T> iterable) {
        this.iterables = iterable.iterables;
        this.iterablesList = iterable.iterablesList;
    }

    @Override
    public Iterator<T> iterator() {
        List<Iterator<T>> iterators = new ArrayList<Iterator<T>>();
        if (iterables != null) {
            for (Iterable<T> iterable : iterables) {
                iterators.add(iterable.iterator());
            }
        } else {
            for (Iterable<T> iterable : iterablesList) {
                iterators.add(iterable.iterator());
            }
        }
        listIterator = iterators.iterator();
        currentIterator = null;
        return this;
    }

    @Override
    public boolean hasNext() {
        if (currentIterator == null || !currentIterator.hasNext()) {
            while (listIterator.hasNext()) {
                Iterator<T> iterator = listIterator.next();
                if (iterator.hasNext()) {
                    currentIterator = iterator;
                    return true;
                }
            }
            return false;
        }
        return currentIterator.hasNext();
    }

    @Override
    public T next() {
        hasNext();
        return currentIterator.next();
    }

    @Override
    public void remove() {
        currentIterator.remove();
    }

    }

I don't know if it is your case. Anyway, you should post your code here.

I think it is a bad design of this part. I guess what the author's thoughts, from the name of this class `CompositeIterable`, it is designed to be a `Iterable` instead of a `Iterator`, so you should call `iterator()` to get an iterator first. But it also implement the `Iterator<T>` interface. Then you can not stop anyone from using it like a `Iterator` and directly call `hasNext()`.

My test code here:

        CompositeIterable<String> iterable = (CompositeIterable<String>) redisson.getKeys().getKeys();
        while (iterable.hasNext()) { // this will throw NullPointerException
            System.out.println(iterable.next());
        }


And the workaround:

        CompositeIterable<String> iterable = (CompositeIterable<String>) redisson.getKeys().getKeys().iterator();
        while (iterable.hasNext()) { // this works fine
            System.out.println(iterable.next());
        }

**Comment by mrniko** [comment]
Fixed
