### ISSUE TITLE
org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (10000 ms) occured for command: (EVAL) with params: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1);

### ISSUE THREAD

**Issue by c8439** [redisson/redisson#1683]
Redis version
4.0.9

Redisson version
3.8.2

redis集群:三主三从，跑了一段时间就会报这个错误，java.io.IOException: 你的主机中的软件中止了一个已建立的连接。

**Comment by jackygurui** [comment]
产生`java.io.IOException: 你的主机中的软件中止了一个已建立的连接`的原因跟服务端有关，不是客户端的问题。

**Comment by kschroiff** [comment]
We are also seeing this (using AWS ElastiCache).

It happens when iterating over the keys in a cache - while trying to determine the total size of the cache (RMap) via accumulating the individual entries ( valueSize(key) ).

(if you have a smarter way to achieve that ... feel free to suggest one ... I haven't found a method for that)

 org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (10000 ms) occured for command: (EVAL) with params: [local result = {}; local idleKeys = {}; local res; if (#ARGV == 4) then res = redis.call('hscan', K..., 3, ParametersCache, redisson__timeout__set:{ParametersCache}, redisson__idle__set:{ParametersCache}, 1551891648164, 8, 10] channel: [id: 0xb8374ba9, L:/172.31.14.99:33254

**Comment by mrniko** [comment]
@kschroiff 

You could use `RMap.sizeInMemory()` method instead.

**Comment by kschroiff** [comment]
@mrniko Ah, thx, that one came in with 3.10 then I reckon - we were still on 3.9.
