### ISSUE TITLE
Question regarding AWS elasticache

### ISSUE THREAD

**Issue by sandeeppilania** [redisson/redisson#1711]
### Expected behavior
I am new redis and AWS elasticache and I am working on a legacy codebase which uses oracle coherent caching. I need to replace it with AWS elasticache and Redission does that. But me being new not able to find how to actually use Redisson for this. Elasticache endpoint is private so that cant be passed to redission client. 
Please help me with providing an example so that i can actually progress on this
Thanks

**Comment by kschroiff** [comment]
Depends on how you configured ElastiCache.

We are e.g. using a cluster with Redis4 and auth. 

First you need to create a config. Let's assume you have a String that stores all the cluster nodes like (3 nodes):

                String hosts="rediss://....,rediss://...,rediss://"

If you'd like to earn some extra points, you could use the ElastiCache API to fetch the nodes (DescribeCacheClustersRequest etc pp) instead of a static setup.

                String[] redisHosts = hosts.split(",");

                ClusterServersConfig clusteredConfig = config.useClusterServers();
                clusteredConfig.addNodeAddress(redisHosts);
                // configure more details here according to your liking 

                if (redisHosts[0].startsWith("rediss"))
                    clusteredConfig.setSslEnableEndpointIdentification(true);

                clusteredConfig.setPassword(pwd);

Then create and check the connection:

        boolean initialConnect = false;
        while (!initialConnect) {
            redissonClient = Redisson.create(config);
            if (redissonClient.getNodesGroup().pingAll())
                initialConnect = true;

            if (!initialConnect) {
                nrl.log(Level.WARNING, "Redis Cache connect NOK yet ... waiting for a sec now ...");
                Thread.sleep(1000L);
            }
        }

And you are ready to go from there.

This will vary slightly depending if you got a single Redis instance or a different AWS Redis version.

**Comment by mrniko** [comment]
@kschroiff 

Thanks for reply!
