### ISSUE TITLE
Fails when trying to read yaml config

### ISSUE THREAD

**Issue by flippy84** [redisson/redisson#1851]
### Expected behavior
To load config values from redisson.yaml
### Actual behavior
Tries to load redisson.json first and aborts even if redisson.yaml is present
### Steps to reproduce or test case
Create a redisson.yaml config and without a redisson.json config present.
### Redis version
4.0.9
### Redisson version
"org.redisson" % "redisson-hibernate-52" % "3.10.0"
### Redisson configuration
singleServerConfig:
  address: "redis://127.0.0.1:6379"
  database: 0

The error is in RedissonRegionFactory.java on line 126. A possible fix would be to nest the config loading like it's done when loading a file without the class loader.

**Comment by mrniko** [comment]
could you share exception and your hibernate configuration?

**Comment by JacekWislicki** [comment]
The problem is in the code of org.redisson.hibernate.RedissonRegionFactory.loadConfig(ClassLoader, String). When parsing an actual YAML file is attempted, com.fasterxml.jackson.core.JsonParseException is thrown. JsonParseException inherits from IOException, so it leads to:
throw new CacheException("Can't parse json config", e);
The method exits with an exception, not entering the YAML part.

**Comment by mrniko** [comment]
Fixed

**Comment by JacekWislicki** [comment]
Great, thank you. When are you planning the next release for Maven?

**Comment by mrniko** [comment]
@JacekWislicki 

during next week
