### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by tigerclawn82** [redisson/redisson#19]
Hi,
   I want to use this inside Android, is it supported?

Thanks

**Comment by dzx1994** [comment]
I used it inside Android，but when Compile，there is a erro message ：
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.

**Comment by mrniko** [comment]
@dzx1994 which version have you used?

**Comment by dzx1994** [comment]
I used the lastes version，and i used JDK 1.8。

**Comment by mrniko** [comment]
@dzx1994 Please try to use 2.7.3 version for Android, because only 2.x.x line Android compatible.

**Comment by dzx1994** [comment]
OK，thanks，i will try it next tomorrow。
