### ISSUE TITLE
Building Cache Memory Problem with Rmap

### ISSUE THREAD

**Issue by terrylakey** [redisson/redisson#1967]
When we use RMap, we find that memory can't be released, which leads to frequent fullgc in the production environment. Is there a solution or optimization update of relevant modules now?
The version we used was 3.8.2

**Comment by mrniko** [comment]
Could you please provide more details? which memory Java or Redis? If java could you provide memory dump?

**Comment by shivendra-kumar** [comment]
We are on version 3.7.2 and are facing the same issue in production where netty threads used by redisson consumed 12GB of total 16GB allocated heap space. One observation i have made is that netty threads had created around 275,000 thread local maps with each consuming around a fixed amount of heap. It all seems to be related with weblogic context aware classloader because it is shared by all the netty threads.  
Since the heap dump is quite large I will be attching the screenshots.

**Comment by mrniko** [comment]
@shivendra-kumar 

You can change follow JVM settings to manage by netty memory allocation https://github.com/netty/netty/blob/a33200ca38990b88315a48637e5ac5da398b100d/buffer/src/main/java/io/netty/buffer/PooledByteBufAllocator.java:
```
-Dio.netty.allocator.tinyCacheSize=...
-Dio.netty.allocator.smallCacheSize=...
-Dio.netty.allocator.normalCacheSize=...
-Dio.netty.allocator.numHeapArenas=...
-Dio.netty.allocator.numDirectArenas=...
-Dio.netty.allocator.useCacheForAllThreads=...
```

Try to set `-Dio.netty.allocator.useCacheForAllThreads=false`

**Comment by shivendra-kumar** [comment]
@mrniko Thnks for the prompt reply. Since the issue is coming in production, would changing these parameters have any impact on responsiveness of calls related to RMap? Also, could this issue be related to FST codec as we are using it to serialize and deserialize the data? 

https://github.com/redisson/redisson/issues/1927

https://github.com/redisson/redisson/issues/1652

**Comment by mrniko** [comment]
@shivendra-kumar 

I don't think it's related to Fst codec since I don't see memory allocation for FSTObjectInput objects in your memory dump

**Comment by shivendra-kumar** [comment]
@mrniko what could be a reasonable value for these:

-Dio.netty.allocator.tinyCacheSize=...
-Dio.netty.allocator.smallCacheSize=...
-Dio.netty.allocator.normalCacheSize=...
-Dio.netty.allocator.numHeapArenas=...
-Dio.netty.allocator.numDirectArenas=...
-Dio.netty.allocator.useCacheForAllThreads=...

We have around 5 GB of data on Redis Server right now which will grow and we usually make 500 get calls per second.

**Comment by terrylakey** [comment]
> Could you please provide more details? which memory Java or Redis? If java could you provide memory dump?

We use java, redis version 4.0.11，and the following is the result of dump analysis
![menu saveimg savepath20190310152254](https://user-images.githubusercontent.com/42146879/54081940-6902ac80-4348-11e9-8ec5-f5c3c9a0947e.jpg)

**Comment by mrniko** [comment]
@terrylakey 

Thanks for the information!

How many RMapCache objects do you use in application?

**Comment by terrylakey** [comment]
@mrniko 
Thanks for your reply. We use RMapCache extensively in user modules, but RMapCache does not release memory.This triggers the fullgc of the JVM, which results in overloading of the server.

**Comment by mrniko** [comment]
@terrylakey 

call `RMapCache.destroy()` method once you don't use object anymore as it recommended on wiki page. This prevents from excessive MapCacheEvictionTask object creation.

**Comment by terrylakey** [comment]
@mrniko 
Thank you for your apply,I will try to accept your advice, If a similar situation occurs after I modifying the code by this way, I hope you will fix this problem in future versions. Thank you.

**Comment by mrniko** [comment]
@shivendra-kumar 

I unable to reproduce any netty's memory leak with 3.10.4 version and follow sample code:
```java
        for (int i = 0; i < 1000; i++) {
            RMap<Object, Object> s = redisson.getMap("test");
            String t = RandomString.make(1000);
            s.put(t, RandomString.make(1000000));
            s.remove(t);
        }
```
