### ISSUE TITLE
session.invalidate()后,key值仍存在

### ISSUE THREAD

**Issue by wy281704862** [redisson/redisson#2019]
### Expected behavior

使用redisson-tomcat，代码中 session.invalidate()后，期望redis中session key值被删除

### Actual behavior

使用redisson-tomcat，代码中 session.invalidate()后，实际redis中session key值没被删除，ttl值为-1

### Steps to reproduce or test case

session.invalidate()

### Redis version

单机版4.0.11

### Redisson version

redisson 开源版 3.10.5

### Redisson configuration

{
   "singleServerConfig":{
      "idleConnectionTimeout":10000,
      "pingTimeout":1000,
      "connectTimeout":10000,
      "timeout":3000,
      "retryAttempts":3,
      "retryInterval":1500,
      "password":password,
      "subscriptionsPerConnection":5,
      "clientName":null,
      "address": "redis://127.0.0.1:6379",
      "subscriptionConnectionMinimumIdleSize":1,
      "subscriptionConnectionPoolSize":50,
      "connectionMinimumIdleSize":32,
      "connectionPoolSize":64,
      "database":0,
      "dnsMonitoringInterval":5000
   },
   "threads":0,
   "nettyThreads":0,
   "codec":{
      "class":"org.redisson.codec.JsonJacksonCodec"
   },
   "transportMode":"NIO"
}

**Comment by jchobantonov** [comment]
Translated issue title from google: After session.invalidate(), the key value still exists

@mrniko current master branch has introduced bug because of this commit:
https://github.com/redisson/redisson/commit/d5ee9a728bf1f58c816349656e46025fdceaf0da#diff-94c54a4b85d461bfd9bad3ab2ff73c95

the commit has removed following code:
```
   if (attrs.isEmpty() || !Boolean.valueOf(String.valueOf(attrs.get("session:isValid")))) {	
                    log.info("Session " + id + " can't be found");	
                    return null;	
   }
```
Which will make RedissonSessionManager.findSession to always create a session object and return it - this is not what we should do though 

Instead of using attrs.isEmpty() and the session:isValid I'm using RMap.isExists() to check if the session exists in redisson

Here is the code that I'm using to get the session attributes in findSesssion method:
```
                Map<String, Object> attrs = null;
                try {
                	RMap map = getMap(id);
                	if (map.isExists()) {
                		attrs = map.getAll(RedissonSession.ATTRS);
                	}
                } catch (Exception e) {
                    log.error("Can't read session object by id: " + id, e);
                }
                
                if (attrs == null) {	
                    log.info("Session " + id + " can't be found");	
                    return null;	
                }

```

Here is the full method code:
```
    @Override
    public Session findSession(String id) throws IOException {
        Session result = super.findSession(id);
        if (result == null) {
            if (id != null) {
                Map<String, Object> attrs = null;
                try {
                	RMap map = getMap(id);
                	if (map.isExists()) {
                		attrs = map.getAll(RedissonSession.ATTRS);
                	}
                } catch (Exception e) {
                    log.error("Can't read session object by id: " + id, e);
                }
                
                if (attrs == null) {	
                    log.info("Session " + id + " can't be found");	
                    return null;	
                }
                
                RedissonSession session = (RedissonSession) createEmptySession();
                session.load(attrs);
                session.setId(id);
                
                session.access();
                session.endAccess();
                return session;
            }
            return null;
        }

        result.access();
        result.endAccess();
        
        return result;
    }

```

The sequence of events are as follow:

1) send request

2) setNew method of the session is invoked and session id set to 281D53ED585AABE776350829398D2285

3) in a jsp I do session.invalidate() which will invoke: RedissonSessionManager.remove(Session, boolean) with session id 281D53ED585AABE776350829398D2285

4) redisson session 281D53ED585AABE776350829398D2285 deleted from Redis (verified)

from application code :

5) call request.getSession(false) - this should return null session as the session should be deleted but the getSession(false) will actually use findSession method with session id 281D53ED585AABE776350829398D2285 - and because we always now create a session without checking if the session exist in Redis in the first place a new session will be created then the access() method will be invoked which will make the session permanent into Redis and at the end we end up with a session in Redis with TTL set to -1

**Comment by jchobantonov** [comment]
@mrniko here is a PR to fix this : https://github.com/redisson/redisson/pull/2070

**Comment by mrniko** [comment]
PR merged
