### ISSUE TITLE
RedissonSessionManager tomcat session timeout in cluster environment even if user is active

### ISSUE THREAD

**Issue by kamesh25** [redisson/redisson#2431]
redisson session manager is creating sessions which is getting expired after 30 minutes even if the user is actively reading the session every few minutes. This is happening in clustering environment, we have AWS redis cluster cache as server and using tomcat redisson session manager. Our application runs on multiple tomcat instances

### Expected behavior
If user is actively reading transactions, same session should be active all the time since the time user is active.
### Actual behavior
Session manager expiring the session after 30 minutes since initial login/session creation time even if user is updating transaction in the beginning and constantly reading the session data.
### Steps to reproduce or test case
web.xml set session timeout as 30 mins
using Tomcat manager like this
 <Manager className="org.redisson.tomcat.RedissonSessionManager"
             configPath="${catalina.base}/redisson.conf"
             readMode="REDIS" updateMode="DEFAULT" broadcastSessionEvents="false"/>
### Redis version
4.0.10
### Redisson version
3.11.5
### Redisson configuration
Cluster configuration
---
clusterServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: null
  slaveConnectionPoolSize: 400
  masterConnectionPoolSize: 400
  nodeAddresses: ["${REDIS_URLS}"]
  keepAlive: false
  tcpNoDelay: false
  sslEnableEndpointIdentification: false
  readMode: "MASTER_SLAVE"
  subscriptionMode: "MASTER"

**Comment by kamesh25** [comment]
Any feedback would be greatly appreciated.

**Comment by mrniko** [comment]
Here is a test for this case https://github.com/redisson/redisson/blob/master/redisson-tomcat/redisson-tomcat-9/src/test/java/org/redisson/tomcat/RedissonSessionManagerTest.java#L46

You need to check in debug if `RedissonSession.expireSession` is called for your case

**Comment by jchobantonov** [comment]
@kamesh25 if the servlet/filter that process your http request do not access the HttpSession, the session in tomcat won't be extended by default unless you have org.apache.catalina.core. StandardHostValve.ACCESS_SESSION set to true. E.g. in order to make sure the session won't expire you need to either access the session from each request that you are making to keep the HttpSession alive or if the request that you expect to keep the session alive do not access the session you need to set the StandardHostValve.ACCESS_SESSSION property to true - see more for this property here : https://tomcat.apache.org/tomcat-8.0-doc/config/systemprops.html
