### ISSUE TITLE
Redisson does not propogate security principal

### ISSUE THREAD

**Issue by exabrial** [redisson/redisson#2589]
see discourse here: http://tomcat.10.x6.nabble.com/Tomcat-doesn-t-propogate-Security-Credentials-during-session-failover-td5094871.html

So the bug comes down to the fact that Redisson uses StandardSession, which does not serialize the security credential _at all_. Redisson should either:

1) Implement/Extend it's own Session object
2) Intentionally replicate security credentials

**Expected behavior**

If a failover event occurs, it should go un-noticed to an end user

**Actual behavior**

The user is logged out during a failover event

**Steps to reproduce or test case**

So you have two tomcat nodes: A & B, clustered in any fashion (forget I
mentioned redisson) of your choosing; let's say they're clustered using the
built in tcp point-to-point replication. Have 5 people logged into an
application on the first server using standard JavaEE APIs
(HttpServletrequest.login) Now turn off server A. Your load balancer starts
sending traffic to server B. Their sessions will be there, BUT they will be
logged out; one has to call HttpServletRequest.login() again. Upon login,
Tomcat destroys the previous session (as it should), nullifying any benefit
for clustering the application in the first place.

**Redisson version**
<lib>org.redisson:redisson-all:3.12.0</lib>
<lib>org.redisson:redisson-tomcat-8:3.12.0</lib>

**Comment by mrniko** [comment]
Thanks for report!

Which authentificator do you use? I guess we need to set `alwaysUseSession = true`. Session will be created in any case during login method invocation.

I'll implement notes field replication as well.

**Comment by exabrial** [comment]
We just use basic authentication. *However, I think serializing those note fields will not accomplish what we need, because those will cause a re-authentication*, which could hit account login limits, but also overload a backend LDAP server when a server failure event occurs.

Instead, we just want the session to be authenticated when it arrives at the new server.  I would suggest adding an option to Serialize the principal itself. Notice StandardSession does not do this intentionally (to avoid writing it to disk):

https://github.com/apache/tomcat/blob/master/java/org/apache/catalina/session/StandardSession.java#L1559
https://github.com/apache/tomcat/blob/master/java/org/apache/catalina/session/StandardSession.java#L234

So a proper fix would handle the Security Principal somehow.

**Comment by mrniko** [comment]
> However, I think serializing those note fields will not accomplish what we need, because those will cause a re-authentication

I think it should help. Constants.REQ_SSOID_NOTE note is used for check
https://github.com/apache/tomcat/blob/e680e0a83312aebc257c67c844f897a633aaac70/java/org/apache/catalina/authenticator/AuthenticatorBase.java#L980

**Comment by mrniko** [comment]
Principal doesn't implement Serializable interface. So it could be a problem to get it persisted.

**Comment by exabrial** [comment]
`java.security.Principal` does not necessarily have to implement Serializable, as it may not be. However, the included Tomcat one does, which covers the vast majority of usage: https://github.com/apache/tomcat/blob/master/java/org/apache/catalina/realm/GenericPrincipal.java That would probably need to be a runtime check: If the developer requests to propagate the security principal, and isn't serializable, do a log.warn to the console.

Also, Constants.REQ_SSOID_NOTE is for cross-application Single Sign On. This wouldn't get set normally unless someone specifically wants to sign onto multiple applications in one tomcat server, and isn't referring to session replication. I certainly wouldn't want to enable cross-application single sign on just to get session replication working properly.

**Comment by wernerreuser** [comment]
Hi, we experience the same issue. 

In a debug session we found the principal to be available in the stored session but it's not used. As a consequence the user has to login again. 

In our case we plan to still use sticky sessions and use the Redis backend only for failover. 

Is there any estimate when we can expect a solution for this issue ? 
I'm in the middle of a project that needs this functionality, need that info to update my project planning. 

I would be happy to test a patch if needed. 

Kind regards,
Werner

**Comment by mrniko** [comment]
> In a debug session we found the principal to be available in the stored session but it's not used. As a consequence the user has to login again.

Could you provide more details? Since principal discussed in this issue is not part of session attributes. This is the cause why it's not get serialized.

**Comment by mrniko** [comment]
@exabrial 

I had finally time to look how DeltaManager handles Principal serialization. It implements own DeltaRequest object which in turn override `setPrincipal` method to store it.

**Comment by mrniko** [comment]
Fixed

**Comment by wernerreuser** [comment]
Hi, 

I'll try to explain as good as I can as I'm not a Java developer, for me this was a infrastructure project and I had one of our Java developers help me with debugging. 

I used Redisson versions: 

redisson-all-3.12.4.jar
redisson-tomcat-7-3.12.4.jar

in Tomcat 7.0.100, jars are placed in tomcat/lib/

Added redisson by this config in context.xml: 

<Manager        className="org.redisson.tomcat.RedissonSessionManager" 
                        configPath="${catalina.base}/conf/redisson.conf" 
                        readMode="REDIS" 
                        updateMode="AFTER_REQUEST" 
                        broadcastSessionEvents="false" 
                        keyPrefix="pzdproductie"
                        persistAuthentication="true" />

redisson.conf points to a single keyDB server for testing. 

When using the keydb-cli monitor command I see the session data being set and retrieved. 

Looking into the session data with P3X Redis UI, I see principal available in the session. 

When testing I started with a sticky session on a single Tomcat server, that seemed to work fine. Failing over to the secondary server failed. The user wasn't logged in anymore. 

Debugging the application and all libraries we see the data being retrieved and available in some sort of map, however when the attributes are copied to the 'real' session object there's some sort of attribute list what attributes are copied to the real session, for some reason the principal isn't in the attribute list and for that reason not copied to the real session object. 

The behaviour of readMode="REDIS" seems a bit unsure. I expected this to force redis being used as session, during debugging it seemed as if it still used the memory based session. Probably why the single server sticky version worked. Staying on the same server has the principal available in the session. 

Is this description enough for you to work with ? If you need more info I can try to append it to the issue. 

Kind regards, 

Werner

**Comment by mrniko** [comment]
@wernerreuser 

Could you try your case with version attached?

[redisson-tomcat-7-3.12.5-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/4460513/redisson-tomcat-7-3.12.5-SNAPSHOT.jar.zip)

**Comment by wernerreuser** [comment]
Yess, thanks !

**Comment by wernerreuser** [comment]
Hi mrniko, 

Testing gave me the following stacktrace: 

apr 10, 2020 12:34:07 PM org.apache.coyote.ajp.AjpNioProcessor process
SEVERE: Error processing request
java.lang.IllegalArgumentException: java.io.IOException: java.lang.RuntimeException: Class org.apache.catalina.realm.GenericPrincipal does not implement Serializable or externalizable
        at org.redisson.RedissonObject.encodeMapValue(RedissonObject.java:338)
        at org.redisson.RedissonMap.putAllOperationAsync(RedissonMap.java:404)
        at org.redisson.RedissonMap.putAllAsync(RedissonMap.java:345)
        at org.redisson.RedissonMap.putAll(RedissonMap.java:282)
        at org.redisson.tomcat.RedissonSession.save(RedissonSession.java:366)
        at org.redisson.tomcat.RedissonSessionManager.store(RedissonSessionManager.java:408)
        at org.redisson.tomcat.UpdateValve.invoke(UpdateValve.java:55)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
        at org.apache.coyote.ajp.AjpNioProcessor.process(AjpNioProcessor.java:175)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:654)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1782)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1741)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: java.lang.RuntimeException: Class org.apache.catalina.realm.GenericPrincipal does not implement Serializable or externalizable
        at org.redisson.codec.FstCodec$2.encode(FstCodec.java:279)
        at org.redisson.RedissonObject.encodeMapValue(RedissonObject.java:336)
        ... 15 more
Caused by: java.lang.RuntimeException: Class org.apache.catalina.realm.GenericPrincipal does not implement Serializable or externalizable
        at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:144)
        at org.nustaq.serialization.FSTClazzInfoRegistry.getCLInfo(FSTClazzInfoRegistry.java:129)
        at org.nustaq.serialization.FSTObjectOutput.getFstClazzInfo(FSTObjectOutput.java:534)
        at org.nustaq.serialization.FSTObjectOutput.writeObjectWithContext(FSTObjectOutput.java:416)
        at org.nustaq.serialization.FSTObjectOutput.writeObjectInternal(FSTObjectOutput.java:327)
        at org.nustaq.serialization.FSTObjectOutput.writeObject(FSTObjectOutput.java:294)
        at org.nustaq.serialization.FSTObjectOutput.writeObject(FSTObjectOutput.java:204)
        at org.redisson.codec.FstCodec$2.encode(FstCodec.java:271)
        ... 16 more

Upgraded Tomcat to 7.0.103 as they implemented the persistAuthentication property on the Manager to be able to save the principal in a SER file while restarting Tomcat, thought they might have had to change te GenericPrincipal to serializable for that. However I still get the same stacktrace unfortunately.

Need any more information from me ?

**Comment by wernerreuser** [comment]
Hi mrniko, 

I was checking the GenericPrincipal code online and found it to be serializable, however this was the Tomcat 9 source tree. Downloaded the sources for 7 and in that version it's not. 

Would it be usefull to test this in a Tomcat 9 environment ? Upgrading to that version needs a few minor adjustments in my configuration but is doable.

**Comment by mrniko** [comment]
You're right GenericPrincipal is not serializable in Tomcat 7.
Here is the Tomcat 9 module.

[redisson-tomcat-9-3.12.5-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/4461331/redisson-tomcat-9-3.12.5-SNAPSHOT.jar.zip)

**Comment by wernerreuser** [comment]
Hi, 

Unfortunately it doesn't solve the issue, this is what happens when I failover to the second Tomcat in the Redis monitor: 

1586519193.133632 [0 10.2.2.170:51762] "PEXPIRE" "pzdproductie:redisson:tomcat_session:D7AD864B65231738501A4451A50F06D2" "7260000"

1586519284.164347 [0 10.2.2.171:47276] "HMSET" "pzdproductie:redisson:tomcat_session:D7AD864B65231738501A4451A50F06D2" "session:thisAccessedTime" "\xf6\x82\xc2\x19\xebcq\x01\x00\x00" "session:lastAccessedTime" "\xf6\x82\x0b\xe2\xe8cq\x01\x00\x00"
1586519284.167295 [0 10.2.2.171:47266] "PEXPIRE" "pzdproductie:redisson:tomcat_session:D7AD864B65231738501A4451A50F06D2" "7260000"
1586519284.170728 [0 10.2.2.171:47278] "HMSET" "pzdproductie:redisson:tomcat_session:D7AD864B65231738501A4451A50F06D2" "session:thisAccessedTime" "\xf6\x82\xc8\x19\xebcq\x01\x00\x00" "session:lastAccessedTime" "\xf6\x82\xc8\x19\xebcq\x01\x00\x00"
1586519284.174253 [0 10.2.2.171:47280] "PEXPIRE" "pzdproductie:redisson:tomcat_session:D7AD864B65231738501A4451A50F06D2" "7260000"
1586519284.181291 [0 10.2.2.171:47282] "HMSET" "pzdproductie:redisson:tomcat_session:D7AD864B65231738501A4451A50F06D2" "session:thisAccessedTime" "\xf6\x82\xd4\x19\xebcq\x01\x00\x00" "session:lastAccessedTime" "\xf6\x82\xc8\x19\xebcq\x01\x00\x00"
1586519284.184366 [0 10.2.2.171:47258] "PEXPIRE" "pzdproductie:redisson:tomcat_session:D7AD864B65231738501A4451A50F06D2" "7260000"
1586519284.187425 [0 10.2.2.171:47254] "HMSET" "pzdproductie:redisson:tomcat_session:D7AD864B65231738501A4451A50F06D2" "session:thisAccessedTime" "\xf6\x82\xd9\x19\xebcq\x01\x00\x00" "session:isNew" "\xef" "session:lastAccessedTime" "\xf6\x82\xd9\x19\xebcq\x01\x00\x00" "session:maxInactiveInterval" "\xf7\x80 \x1c" "session:isValid" "\xf0" "session:creationTime" "\xf6\x82\xc6\xb4\xa3cq\x01\x00\x00"
1586519284.189973 [0 10.2.2.171:47246] "PEXPIRE" "pzdproductie:redisson:tomcat_session:D7AD864B65231738501A4451A50F06D2" "7260000"

The first line is Tomcat running at 10.2.2.170, the session is initiated there, the following lines do not even show HGET commands from Tomcat to redis, it doesn't seem to fetch the session information from Redis. The first Tomcat does is every request as long as I keep the session on that instance. 

Perhaps the issue is something else, see this screenshot: 

![image](https://user-images.githubusercontent.com/8298388/78989292-8699db00-7b33-11ea-8552-2c6d6dfa72c3.png)

You can see there's a few non standard attributes in the session (licenseBase@pje9gd9z, principal) 

Those two are not available in the list of session attributes that are copied from the attribute map retrieved from redis and thus not copied into the session. That seems to be the reason we can't continue the session on the second Tomcat server.

**Comment by mrniko** [comment]
I forgot to add PRINCIPAL_ATTR and AUTHTYPE_ATTR in org.redisson.tomcat.RedissonSession#ATTRS list.

**Comment by mrniko** [comment]
Here is updated lib

[redisson-tomcat-9-3.12.5-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/4464538/redisson-tomcat-9-3.12.5-SNAPSHOT.jar.zip)

**Comment by mrniko** [comment]
Fixed

**Comment by wernerreuser** [comment]
Thanks mrniko !

**Comment by mrniko** [comment]
@wernerreuser 

Have you recheck it with the version attached above?

**Comment by wernerreuser** [comment]
Not yet, had a pretty busy day... Will test asap. 
Can I use the Tomcat 7 version or does it still contain the not serializable genericprincipal ?

**Comment by wernerreuser** [comment]
I can test both if you want, 7 and 9 ?

**Comment by mrniko** [comment]
I'm afraid Tomcat 7 can't be used.

**Comment by wernerreuser** [comment]
No problem, I'll test 9

**Comment by wernerreuser** [comment]
Sorry I had you waiting for the results... but... It works !!!
Just tested the 9 version by the way, didn't test the 8 fix and 7 was not necessary.

Many thanks for fixing this so quickly !

Kind regards, 

Werner

**Comment by mrniko** [comment]
@wernerreuser 

Thanks for your feedback!
