### ISSUE TITLE
Blocking commands connected to Redis Cluster aren't resubscribed after Master node failover

### ISSUE THREAD

**Issue by mrniko** [redisson/redisson#2832]

**Comment by mrniko** [comment]
Fixed

**Comment by eng7miky** [comment]
@mrniko  we are facing problem related to connections broken between Redisson and Redis. we faced a lot of RedisTimeout Exception (unable to get connections). what is the right way to re-initiate the connection ? shall we shutdown and initialize ?

**Comment by mrniko** [comment]
@eng7miky 

Did you try to set `pingConnectionInterval` setting?

**Comment by eng7miky** [comment]
I am trying it from a while but I faced also a problem that not all results return from batch request (response.size != requested keys) and redisson don't throw any problem. it is a connection problem? or in this case how to recover this kind of issue? (just retry the batch again or re-initialize the client?

**Comment by mrniko** [comment]
> I am trying it from a while but I faced also a problem that not all results return from batch request (response.size != requested keys) and redisson don't throw any problem

Can you provide any test case to reproduce this?

**Comment by eng7miky** [comment]
I cannot reproduce the problem of not equal size between requests and responses but when it happened in the production, the problem kept happeningfrom request to another until I restarted the application so the client started to return the whole batch requested as expected. that's why I am asking if we can refer to recovery process for that client in case of unexpected problems between the client and Redis.
