### ISSUE TITLE
when GenerationType is IDENTITY, test failed

### ISSUE THREAD

**Issue by luyuanx2** [redisson/redisson#2864]
![image](https://user-images.githubusercontent.com/26129033/85224260-910e0600-b3fb-11ea-8499-7fd452646ca9.png)
![image](https://user-images.githubusercontent.com/26129033/85224267-a08d4f00-b3fb-11ea-99c4-8a21e3f8cd44.png)

**Comment by mrniko** [comment]
It's not a bug since `afterInsert` method call commented out in hibernate `EntityIdentityInsertAction` used for this type of strategy:

https://github.com/hibernate/hibernate-orm/blob/fa952863cf7effa61c8a3b63f72805e7d1be8b79/hibernate-core/src/main/java/org/hibernate/action/internal/EntityIdentityInsertAction.java#L138

Without this method call it's impossible to update cache.
