### ISSUE TITLE
more connected clients than allowed

### ISSUE THREAD

**Issue by Aviisek** [redisson/redisson#2944]
I have setup redis client with **setConnectionPoolSize(64)** . At heavy load when I check the Redis server it shows connected clients to be  284. I am running 4 replicas of application. I expect it should never go above 64*4 = 256.  

No other app is currently connected nor any manual connection has been done to the redis server. 
I am not sure whats the exact reason here.

Redis version : 4
Redisson client version : 3.12.5

**Comment by mrniko** [comment]
Do you use RBatch object?

**Comment by mrniko** [comment]
How many Pubsub connections did you define in configuration?

**Comment by avisek1269** [comment]
@mrniko I have not defined any Pubsub connection by myself. Its using default one with subscriptionConnectionMinimumIdleSize = 1. 

I am not using any PubSub functionality, so I would expect it to be at 1 all the time. 
So even if I consider 4 connections for Pubsub accounting 4 replicas, still total connections seems to be more than allowed with redis server.

**Comment by BEWINDOWEB** [comment]
same redis server version 4.x & same redis client version 3.12.5 & same performace 260+ connections, and it's single server with ConnectionPoolSize(64) and no subscriptionConnection settings :
```
ss|grep 6379|wc -l
265
```
I've tested that set subscriptionConnection to 0, nothing changed.
it will cause that, when application pod crashed or network corrupted, the redis server will stuck at so many connetion requests in serveral seconds due to redis single thread, and it cannot execute any other command.

This can only be reproduced in high concurrency scene.

BTW, we are upgrade from version below 3.10.1, because  3.10.1 fix the issue "https://github.com/redisson/redisson/issues/1811"(The connection can not reconnect), maybe this patch cause this uncontrolled connections issue?

We are testing 3.14.1 now.

**Comment by ctron-te** [comment]
@BEWINDOWEB did you finish your testing with 3.14.1? I think we might be experiencing the same issue.
