### ISSUE TITLE
suitable configuration settings

### ISSUE THREAD

**Issue by 4fath** [redisson/redisson#3138]
hello,

there are numerous connection settings like connectionPoolSize, connectionMinimumIdleSize so forth so on..
for instance, when I put 100 for connectionPool, it use all of them in course of some load (I monitor redis server with redis-exporter). then I increased it to 200, then it started to use 200. 
My question is how can I find suitable settings, is there any hint which I can refer?

**Comment by matthewbogner** [comment]
I think another way to phrase this question is, how do we monitor the utilization of the connection pool and netty thread pool?

Personally, I'm using Redisson within a dropwizard application, and would like to be able to monitor utilization of the internal cxn/thread pools so that I can have better visibility into when a bump in the configured settings (according to [suggested FAQ tweaks](https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it)) is actually necessary. 

I'm happy to do the dirty work of wiring individual metrics into our monitoring, but it isn't clear where to get these utilization numbers from.

**Comment by mrniko** [comment]
@4fath 

Connection pool settings are unique per use case. You need to execute performance tests with different values before you find the best ones.

@matthewbogner 

You can get follow connection pool utilization metrics - https://github.com/redisson/redisson/wiki/14.-Integration-with-frameworks#metrics-per-redis-node
