### ISSUE TITLE
deleteByPatternAsync lua script error

### ISSUE THREAD

**Issue by sjcoder2020** [redisson/redisson#3211]
I am currently using AWS Redis Elasticache cluster with a simple setup 
Redis Version 5.X
1 shard, 2 replica

```
final RBatch batch = redissonClient.createBatch();
batch.getKeys().deleteByPatternAsync(keyPattern.toString());
return batch.executeAsync()
                     .exceptionally(t -> LOG.warn("error when deleting"));
```

I sometimes get an error like below where keyPattern is "test-key*" which is confusing considering that I only have 1 shard.

`org.redisson.client.RedisException: ERR Error running script (call to f_101594a3a4c130bec4a4a379cda6d00cb1c5ff1a): @user_script:1: @user_script: 1: Lua script attempted to access a non local key in a cluster node . channel: [id: 0xf885399a, L:/172.25.76.177:60542 - R:/172.18.11.62:6379] command: (EVAL), params: [local keys = redis.call('keys', ARGV[1]) local n = 0 for i=1, #keys,5000 do n = n + redis.call('del'..., 0, test-key*] (Most recent call first)`

Any idea what could be going here?

**Comment by mrniko** [comment]
unable to reproduce it with latest version

**Comment by lazycoder20** [comment]
Not sure if the configuration matters so just posting it here incase you see something that should be configured when using RBatch.

```
            cacheConfig
                .useClusterServers()
                .addNodeAddress(redisConfiguration.getCacheUrl())
                .setMasterConnectionPoolSize(redisConfiguration.getConnectionPoolSize())
                .setConnectTimeout(redisConfiguration.getConnectTimeout())
                .setTimeout(redisConfiguration.getRequestTimeout())
                .setRetryAttempts(redisConfiguration.getRetryAttempts())
                .setRetryInterval(redisConfiguration.getRetryInterval());
```

I am thinking of falling back to the normal way of deleting by pattern that uses scan under the hood instead of this RBatch lua script that is used in client library. What do you think, which one is preferred?

`redissonClient.getKeys().deleteByPatternAsync(keyPattern.toString())
`

I opted for 1 shard considering that RBatch wouldn't work well otherwise for pattern based deleting. But if I fallback to above, can I then use multiple shards? Does scan operation and delete by `redissonClient.getKeys().deleteByPatternAsync` work well with multiple shards?

**Comment by mrniko** [comment]
`Lua script attempted to access a non local key in a cluster node` this might related to Redis vendor limitations. Which Redis hosting do you use?

**Comment by lazycoder20** [comment]
AWS Elasticache Redis

**Comment by mrniko** [comment]
I managed to reproduce the issue. Unfortunatelly this method can't be implemented for usage in batch with Redis cluster.

**Comment by mrniko** [comment]
IllegalStateException added
