### ISSUE TITLE
生产环境由于阿里云网络故障恢复后，无法自动重新建立链接

### ISSUE THREAD

**Issue by cuipengcx** [redisson/redisson#3281]
Redission Version: 3.6.7

错误信息:
org.redisson.client.RedisTimeoutException: Redis server response timeout (2000 ms) occured for command: (EVAL) with params: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, AOS:LOCK:FACTORY_STOCK:P180201109003-1001014, 20000, 1d3f102f-07e9-411f-9475-48a55ef14717:90] channel: [id: 0x3c1eb21f, L:/172.17.71.254:34546 - R:r-uf6qgqpdnv4ck7x45w.redis.rds.aliyuncs.com/10.97.39.124:6379]
	at org.redisson.command.CommandAsyncService$11.run(CommandAsyncService.java:682)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mrniko** [comment]
Try to update Redisson. There are several issues have been fixed since version you use.

**Comment by cuipengcx** [comment]
> Try to update Redisson. There are several issues, related to failover handling, have been fixed since version you use.

which version was fixed？Thank you！

**Comment by jianshengli** [comment]
which version was fixed？Thank you！

**Comment by TokenJan** [comment]
> 02-Jul-2020 - 3.13.2 released
Feature - Partitioning (sharding) of Redis setup using ShardedRedisson object
Feature - CLUSTERDOWN error handling
Feature - getConfig, setConfig methods added to RedisNode interface
Fixed - empty sentinels list handling
Fixed - RMapCache.clear() method clears maxSize option
Fixed - Redisson slowdowns access to hibernate in fallback mode
Fixed - Sentinel hostname isn't used for ssl connection during Redisson startup
Fixed - RBloomFilter methods throw NPE if RedisException thrown
Fixed - RAtomicDouble.getAndSet() method throws NPE
Fixed - RAtomicLong.getAndSet() method throws NPE
Fixed - ClassCastException thrown in Tomcat environment
Fixed - RSetMultimap.get().delete() and RListMultimap.get().delete() methods throw exception
Fixed - blocking commands connected to Redis Cluster aren't resubscribed after Master node failover <--
Fixed - connection leak if SSL connection got reconnected

I think this issue is fixed by this version.
