### ISSUE TITLE
Can I make Redis soft dependency?

### ISSUE THREAD

**Issue by hiravoza** [redisson/redisson#3375]
I am trying to use this library as my cache engine in my JPA application. As of now I understand if I configure this in my app - the app won't start if the Redis isn't running. Can I make this a soft dependency like if Redis server isn't running start the app without L2 cache?

**Comment by sounroy** [comment]
Hi Hiravoza,

Were you able to use reddison hibernate as second level cache?

I am getting the following error.
Getting connection refused error while trying to use reddison-hibernate as hibernate second level cache

Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:6379
app_1    | Caused by: java.net.ConnectException: Connection refused
app_1    |      at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_292]
app_1    |      at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716) ~[na:1.8.0_292]
app_1    |      at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
app_1    |      at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
app_1    |      at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
app_1    |      at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
app_1    |      at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
app_1    |      at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
app_1    |      at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.55.Final.jar!/:4.1.55.Final]
app_1    |      at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.55.Final.jar!/:4.1.55.Final]
app_1    |      at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.55.Final.jar!/:4.1.55.Final]
app_1    |      at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_292]
app_1    |

**Comment by mrniko** [comment]
@sounroy

> Getting connection refused error while trying to use reddison-hibernate as hibernate second level cache

You need to check your connection with Redis

**Comment by sounroy** [comment]
> @sounroy
> 
> > Getting connection refused error while trying to use reddison-hibernate as hibernate second level cache
> 
> You need to check your connection with Redis

@mrniko  this is my connection string in reddidon.yml. 
address: "redis://localhost:6379"

**Comment by mrniko** [comment]
Implemented in https://github.com/redisson/redisson/issues/3042
