### ISSUE TITLE
Redis renewExpiration  ttl problem

### ISSUE THREAD

**Issue by nomar22** [redisson/redisson#3714]
**Expected behavior**
Allways renew the ttl key .

**Actual behavior**
after looses a lock and try to aquire it again, sometimes the renewal feature doesn't work as it supposed

**Steps to reproduce or test case**
To reproduce it I had to use debug stop the execution before this call

![image](https://user-images.githubusercontent.com/3428451/124617554-eeda8800-de6e-11eb-95e5-715cdfee2031.png)

with redis client remove the key.

Then release the flow. 

![image](https://user-images.githubusercontent.com/3428451/124617951-42e56c80-de6f-11eb-976e-ba454d4bfb39.png)

 if the key does'nt exists the renewal doesn't fire for this specific key, and it's everything ok 

So my code aquire this lock again since it's not the owner, and everything seems to work except that it doesn't renew the ttl key lock because of this

![image](https://user-images.githubusercontent.com/3428451/124618202-80e29080-de6f-11eb-8d8e-a1c0f05ffaae.png)

In my point of view if you add 
  cancelExpirationRenewal(threadId)
when the renewal fails , it solves the problem

![image](https://user-images.githubusercontent.com/3428451/124620983-d15aed80-de71-11eb-8628-fc1c7591c189.png)

**Redis version**
6.0.5
**Redisson version**
3.16.0
**Redisson configuration**
default config.

**Comment by Aqu1nt** [comment]
This bug also bit us - we're using permanent Redisson Locks to determine a "primary" instance within all service instances -> The instance who is able to aquire & hold the lock will be the "primary" instance.

During a Redis Upgrade the TTL of the locks expired during failover and therefore the renewal failed.

Without this MR those locks will now NEVER be renewed for the lifetime of the instance - this causes problems because suddenly multiple instances are able to aquire the lock (& immediatley loose it again) - causing a really unexpected inconsistency in the system.

**Comment by Cesarla** [comment]
I've experienced a similar problem to what @Aqu1nt describes after a failover in a Redis sentinel setup.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/pull/3716
