### ISSUE TITLE
Intermittently, after Azure Redis maintenance, Redis pubsub channel is removed and Redisson listeners subscribe successfully but don't deliver any messages

### ISSUE THREAD

**Issue by taksamit** [redisson/redisson#3940]
We observed and intermittent issue after Azure Redis scheduled maintenance. 
The issue occurred on one of service pods; other pods didn't experience the same issue.
Our application creates a pub/sub listener, publishes messages every second but doesn't get these events back; as a result it thinks Redisson-Redis connection is broken and so resubscribes, but the same issue occurs even with new listeners. The issue has persisted for many hours, even though Redis maintenance was fairly short.

In attached logs (both from our service and from Redisson) following can be seen:

// we subscribe to vrckc-redis-hb-7bbb8f6c4b-hb67l topic
08/11/2021 11:08:24.825 [RMS] INFO com.avaya.vrc.kc.ixil.RedissonMessageSubscriber subscribe() vrckc-redis-hb-7bbb8f6c4b-hb67l => sl=1964278001, l=1880120247

// we publish messages on this topic every second and Redisson APIs return without errors
08/11/2021 11:08:24.827 [RMS] TRACE com.avaya.vrc.kc.ixil.RedissonMessageSubscriber publishHeartbeat() 1636369704825 in 1 ms
08/11/2021 11:08:25.827 [RMS] TRACE com.avaya.vrc.kc.ixil.RedissonMessageSubscriber publishHeartbeat() 1636369705825 in 2 ms
08/11/2021 11:08:26.828 [RMS] TRACE com.avaya.vrc.kc.ixil.RedissonMessageSubscriber publishHeartbeat() 1636369706826 in 2 ms
08/11/2021 11:08:27.828 [RMS] TRACE com.avaya.vrc.kc.ixil.RedissonMessageSubscriber publishHeartbeat() 1636369707826 in 2 ms
08/11/2021 11:08:28.828 [RMS] TRACE com.avaya.vrc.kc.ixil.RedissonMessageSubscriber publishHeartbeat() 1636369708826 in 2 ms
08/11/2021 11:08:29.828 [RMS] TRACE com.avaya.vrc.kc.ixil.RedissonMessageSubscriber publishHeartbeat() 1636369709826 in 2 ms
// we didn't get notified about any of 6 messages sent before so we think Redisson-Redis connection is down
08/11/2021 11:08:30.827 [RMS] WARN com.avaya.vrc.kc.ixil.RedissonMessageSubscriber publishHeartbeat() heartbeats not received in a timely manner. c=1636369710827, lr=1636369704825, lp=1636369709826

**Expected behavior**
Published messages are received back

**Actual behavior**
Published messages are not received back

**Steps to reproduce or test case**
Issue intermittent, observed after Azure Redis scheduled maintenance on one of service pods; other pods didn't experience the same issue

**Redis version**

**Redisson version**
3.15.6

**Redisson configuration**
config: ---
clusterServersConfig:
idleConnectionTimeout: 10000
connectTimeout: 15000
timeout: 3000
retryAttempts: 3
retryInterval: 1500
password: "..."
subscriptionsPerConnection: 5
sslEnableEndpointIdentification: true
sslProvider: "JDK"
pingConnectionInterval: 5000
keepAlive: true
tcpNoDelay: true
nameMapper: !<org.redisson.api.DefaultNameMapper> {}
loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
slaveConnectionMinimumIdleSize: 24
slaveConnectionPoolSize: 64
failedSlaveReconnectionInterval: 3000
failedSlaveCheckInterval: 60000
masterConnectionMinimumIdleSize: 24
masterConnectionPoolSize: 64
readMode: "MASTER"
subscriptionMode: "SLAVE"
subscriptionConnectionMinimumIdleSize: 1
subscriptionConnectionPoolSize: 50
dnsMonitoringInterval: 5000
natMapper: !<org.redisson.api.DefaultNatMapper> {}
nodeAddresses:

    "rediss://ixcc-qa-redis.redis.cache.windows.net:6380"
    scanInterval: 5000
    checkSlotsCoverage: true
    threads: 16
    nettyThreads: 16
    codec: !<org.redisson.client.codec.StringCodec> {}
    referenceEnabled: true
    transportMode: "NIO"
    lockWatchdogTimeout: 30000
    reliableTopicWatchdogTimeout: 600000
    keepPubSubOrder: true
    useScriptCache: false
    minCleanUpDelay: 5
    maxCleanUpDelay: 1800
    cleanUpKeysAmount: 100
    nettyHook: !<org.redisson.client.DefaultNettyHook> {}
    useThreadClassLoader: true
    addressResolverGroupFactory: !<org.redisson.connection.DnsAddressResolverGroupFactory> {}
[fragment.log](https://github.com/redisson/redisson/files/7496726/fragment.log)

**Comment by avcad** [comment]
I might also be running into the same problem. (3.16.4, standalone). This typically works and I cannot reproduce it. 
When the problem happens I see a onDisconnect() but I don't have a subsequent onConnect() and onSubscribe()

I don't know what causes the onDisconnect(). I have no errors in the client logs or in Redis. Other operations (e.g publish) continue to work fine. I checked Redis after hitting the problem and saw the client had many regular connections established and one pubsub. We have 7 topics, and max 5 per connection, so I should have had 2 pubsub connections. One went missing.

I also implemented a watchdog but I don't have any recovery logic - it just prints the problem was detected
I was thinking of calling this when the problem happens: getConnectionManager().getSubscribeService().reattachPubSub()
I am now trying to reproduce with Redisson debug to see if I have the "ConnectionWatchdog tryReconnect"
message in the logs.

**Comment by taksamit** [comment]
Hi @avcad, thank you for your comment. 
Apologies for a basic question (I'm fairly new to Redis) but could you please tell me how do you check on Redis side pub/sub connections? We're running in Azure Redis so I don't have Redis logs but I do have access to Redis CLI (at least some commands).
Also, strangely enough, in my case other pub/sub listeners continue to work fine i.e. do deliver messages, and it's only one topic that's affected by this issue. Based on this I'm not sure if `getConnectionManager().getSubscribeService().reattachPubSub()` would help but it's an interesting idea.

**Comment by taksamit** [comment]
I just checked on Redis and the pub/sub channel doesn't exist:
```
pubsub channels vrckc-redis-hb*
vrckc-redis-hb-7bbb8f6c4b-925qh
```

**Comment by avcad** [comment]
You can also use `client list type pubsub`. sub= shows number of subscriptions. You can filter by IP

@mrniko , I tried using reattachPubSub(RedisPubSubConnection redisPubSubConnection), but that only seems to work for the last connection. e.g. if I have 5 subscriptions per connection, and 13 topics, it will only do the last 3. The previous ones
are skipped because they don't exist in entry2PubSubConnection. is that expected?

So then I changed my code to use reattachPubSub(int slot). That seems to work. I see all the UNSUBSCRIBE/SUBSCRIBE triggering, although a bit odd, the status listener doesn't trigger for all the unsubscribes but It does trigger for all subscribes.

**Comment by avcad** [comment]
sample code for reattachPubSub(RedisPubSubConnection redisPubSubConnection)

```		
               Config config = new Config();		
		config.useSingleServer().setAddress( "redis://127.0.0.1:6379" );
		Redisson redisson = (Redisson)Redisson.create(config);
		
		PublishSubscribeService pubsubService = redisson.getConnectionManager().getSubscribeService();
		
		final int NUM_TOPICS=8;

		for ( int t=0; t<NUM_TOPICS; t++) {
			RTopic topic = redisson.getTopic("topic_"+t);
			topic.addListener( TOPIC_STATUS_LISTER );
			topic.addListener( String.class, new org.redisson.api.listener.MessageListener<String> ()  {
				@Override
				public void onMessage(CharSequence channel, String msg) {
				}
			});
		}
		
		final Set <Integer> loggedConnections = new HashSet <> ();
		
		for ( int t=0; t<NUM_TOPICS; t++) {
			final String topic = "topic_"+t;			
			final PubSubConnectionEntry pusubce = pubsubService.getPubSubEntry(new ChannelName(topic));
			if ( pusubce == null ) { 
				System.out.println("Topic " + topic + " does not have a connection entry");
				continue;
			}
			final RedisPubSubConnection pubsubconn = pusubce.getConnection();
			
			if (!loggedConnections.contains(pubsubconn.hashCode())) {
				System.out.println( "Connection: " + pubsubconn + "\n\tChannels: " + pubsubconn.getChannels().keySet() );
				pubsubService.reattachPubSub(pubsubconn);
				loggedConnections.add( pubsubconn.hashCode() );
			}
		}
```

output. only 5/6/7 (belonging to last connection) are resubscribed:

```
2021-11-09 14:49:26 INFO org.redisson.Version logVersion Redisson 3.16.4
2021-11-09 14:49:29 INFO org.redisson.connection.pool.ConnectionPool$1 lambda$run$0 1 connections initialized for 127.0.0.1/127.0.0.1:6379
2021-11-09 14:49:29 INFO org.redisson.connection.pool.ConnectionPool$1 lambda$run$0 24 connections initialized for 127.0.0.1/127.0.0.1:6379
Subscribe: topic_0
Subscribe: topic_1
Subscribe: topic_2
Subscribe: topic_3
Subscribe: topic_4
Subscribe: topic_5
Subscribe: topic_6
Subscribe: topic_7
Connection: RedisPubSubConnection@2069086239 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0x956f30df, L:/127.0.0.1:54455 - R:127.0.0.1/127.0.0.1:6379], currentCommand=null, usage=0]
	Channels: [topic_1, topic_0, topic_3, topic_2, topic_4]
Connection: RedisPubSubConnection@-386212963 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0x00dfb7c6, L:/127.0.0.1:54479 - R:127.0.0.1/127.0.0.1:6379], currentCommand=null, usage=0]
	Channels: [topic_5, topic_7, topic_6]
onUnsubscribe: topic_5
onUnsubscribe: topic_7
Subscribe: topic_5
2021-11-09 14:49:29 INFO org.redisson.pubsub.PublishSubscribeService lambda$subscribe$27 listeners of 'topic_5' channel to '[addr=redis://127.0.0.1:6379]' have been resubscribed
Subscribe: topic_6
Subscribe: topic_7
2021-11-09 14:49:30 INFO org.redisson.pubsub.PublishSubscribeService lambda$subscribe$27 listeners of 'topic_6' channel to '[addr=redis://127.0.0.1:6379]' have been resubscribed
2021-11-09 14:49:30 INFO org.redisson.pubsub.PublishSubscribeService lambda$subscribe$27 listeners of 'topic_7' channel to '[addr=redis://127.0.0.1:6379]' have been resubscribed
```

**Comment by taksamit** [comment]
thank you @avcad 
In my case though the channel itself is missing on Redis side so not sure if reconnecting Redisson pub/sub connections would resolve the issue.
I have raised a support issue with Microsoft to explain if channel could have been removed as part of redis maintenance.
From Redisson client I think I'd need to figure out that this scenario has happened i.e. lack of channel on Redis and how to force Redisson to recreate the channel.

**Comment by mrniko** [comment]
@taksamit 

Redisson sends PING over pubsub channel and reconnect it in case of fail.

**Comment by taksamit** [comment]
Hi @mrniko , I mentioned earlier that pubsub channel is missing on Redis side (perhaps lost during Redis maintenance). It seems to me that ping/pong will not detect missing pubsub channel.
How can a Redisson client detect this situation (missing pubsub channel on Redis side) and force Redisson to re-create the channel?

**Comment by avcad** [comment]
Hi @taksamit, the reason why the channel is gone, is probably because the connection was lost. You can check connections with 
client list type pubsub command. What mrniko said is that if Redisson tries to do a PING and it finds the connections is broken, it will try to reconnect then, but you have "pingConnectionInterval: 5000" in the configuration, so I guess that didn't help

**Comment by mrniko** [comment]
@avcad 

Attempt to reconnect is made every 5 seconds in this case.

**Comment by avcad** [comment]
Thanks. I will try to reproduce with debug trace.

**Comment by taksamit** [comment]
Hi @mrniko , apologies but I don't understand how this is supposed to work. I included Redisson TRACE logs where PING, PONG and PUBLISH are seen, and application tried thousands of time to subscribe but no new messages are reported.

**Comment by mrniko** [comment]
Hi @taksamit,

PingConnectionHandler closes channel due to Ping response timeout. Once it's closed ConnectionWatchdog.channelInactive() method invoked and on successful reconnection ConnectionWatchdog.reattachPubSub() is called. Last method reconnect current pubsub channels.

**Comment by taksamit** [comment]
Hi @mrniko , so the suspicion is that there was a PING response timeout (during Redis maintenance) and Redisson called ConnectionWatchdog.channelInactive()?
Given that Redisson re-connected to Redis (PING/PONG seen in attached logs) should current pubsub channels have been reconnected?
If our application were to call ConnectionWatchdog.reattachPubSub() would it recreate missing pubsub channel in Redis?

**Comment by avcad** [comment]
That's what I was trying to do above.
So in my case I see an onDisconnect() but I don't have a matching/subsequent onConnect() and onSubscribe() ( which I get when I test and try to reproduce). 

onDisconnect() triggers from ConnectionWatchdog.channelInactive(). So Redisson knows the connection was lost, but the tryReconnect doesn't work somehow. 

so same as what you were asking, if the custom watchdog ( I have one similar to yours) detected the connection is not working, 
what is the best way to programmatically try force the subscribe command?
I came up with this earlier but I haven't tested it.  
// not ideal, in standalone Redis, this means ALL topics, which is not good.
final int slot = redisson.getConnectionManager().calcSlot( myTopicName );
redisson.getConnectionManager().getSubscribeService().reattachPubSub( slot );

another option would be to call  - this might work better. removeAllListeners should force the UNSUBSCRIBE and SUBSCRIBE  - Redisson can try to use a new connection for the subscribe (or print an error)
topic.removeAllListeners()
topic.addListener(.. ) 

As the problem is sporadic, having DEBUG enabled all the time it's very difficult. It's possible to enable after we hit the problem but much harder to capture when the onDisconnect() happens.  but with the custom watchdog, I can add any debug code I want to dump the connections/listener/states. etc.

**Comment by mrniko** [comment]
@taksamit 

> so the suspicion is that there was a PING response timeout (during Redis maintenance) and Redisson called ConnectionWatchdog.channelInactive()?

Yes, it's called.

> Given that Redisson re-connected to Redis (PING/PONG seen in attached logs) should current pubsub channels have been reconnected?

Yes

> If our application were to call ConnectionWatchdog.reattachPubSub() would it recreate missing pubsub channel in Redis?

Yes

**Comment by taksamit** [comment]
Thank you @mrniko, so if I understand correctly, if we get into this scenario we can try to recover using `ConnectionWatchdog.reattachPubSub()`. 
One more question: is there some way to programmatically detect that pubsub channel on Redis side is missing? For example some way to send `pubsub channels <channel_name>` command to Redis using Redisson library? If yes, then we could call `ConnectionWatchdog.reattachPubSub()` only after checking that it's actually needed

**Comment by SplotyCode** [comment]
Over AsyncCommandExecutor you can send any redis command. But luckily there is RTopic#countSubscribers() in never redisson versions

**Comment by mrniko** [comment]
@taksamit 

I agree with @SplotyCode. You can use `countSubscribers()` to count listeners on Redis side.

**Comment by taksamit** [comment]
thank you @mrniko and @mrniko : I'll try this

**Comment by mrniko** [comment]
It might be related to this issue https://github.com/redisson/redisson/issues/3957
