### ISSUE TITLE
Incorrect connection calculations in version 3.16.5 and 3.16.6

### ISSUE THREAD

**Issue by dkorotych** [redisson/redisson#4011]
I have a limit of 20 connections per server and in previous versions the initialization was correct. But in version 3.16.5, the SlaveConnectionPool was initialized, which creates 24 connections by default. But I cannot reduce their number for configuration in single server mode and I cannot disable the creation of this pool either.

**Expected behavior**
2021-12-08 12:04:26.535    INFO 297287 --- [           main] org.redisson.Version                     : Redisson 3.16.4
2021-12-08 12:04:26.806    INFO 297287 --- [isson-netty-2-3] o.r.c.pool.MasterConnectionPool          : 4 connections initialized for 127.0.0.1/127.0.0.1:6383
2021-12-08 12:04:26.808    INFO 297287 --- [isson-netty-2-3] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for 127.0.0.1/127.0.0.1:6383

**Actual behavior**
2021-12-08 12:06:41.232    INFO 297579 --- [           main] org.redisson.Version                     : Redisson 3.16.5
2021-12-08 12:06:41.540    INFO 297579 --- [isson-netty-2-2] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for 127.0.0.1/127.0.0.1:6383
2021-12-08 12:06:41.540    INFO 297579 --- [isson-netty-2-4] o.r.c.pool.PubSubConnectionPool          : 1 connections initialized for 127.0.0.1/127.0.0.1:6383
2021-12-08 12:06:41.544    INFO 297579 --- [isson-netty-2-4] o.r.c.pool.MasterConnectionPool          : 4 connections initialized for 127.0.0.1/127.0.0.1:6383
2021-12-08 12:06:41.553    INFO 297579 --- [isson-netty-2-4] o.r.connection.pool.SlaveConnectionPool  : 24 connections initialized for 127.0.0.1/127.0.0.1:6383

**Steps to reproduce or test case**

**Redis version**

**Redisson version**
3.16.5,...

**Redisson configuration**
single server

**Comment by avcad** [comment]
seems to be caused by this commit 
https://github.com/redisson/redisson/commit/8de06075fbc328011b7b399312dfbe2bde0c2374

**Comment by mrniko** [comment]
@avcad Thanks for pointing out.

Fixed

**Comment by avcad** [comment]
@mrniko, Thanks!

btw, I am not running into this, but FYI, 

I tested and SingleServer works fine, but if I test MasterSlave and I don't add slaves (we have done that in the past)
I see 2 additional slave pools

Config config = new Config();
config.useMasterSlaveServers().setMasterAddress( "redis://127.0.0.1:6379");		
Redisson.create(config);

11:41:33.586 [main] INFO org.redisson.Version - Redisson 3.16.7.SNAPSHOT
11:41:40.211 [redisson-netty-2-24] INFO org.redisson.connection.pool.MasterPubSubConnectionPool - 1 connections initialized for 127.0.0.1/127.0.0.1:6379
11:41:40.225 [redisson-netty-2-25] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for 127.0.0.1/127.0.0.1:6379
11:41:40.292 [redisson-netty-2-32] INFO org.redisson.connection.pool.MasterConnectionPool - 24 connections initialized for 127.0.0.1/127.0.0.1:6379
11:41:40.299 [redisson-netty-2-5]  INFO org.redisson.connection.pool.SlaveConnectionPool - 24 connections initialized for 127.0.0.1/127.0.0.1:6379
11:41:40.331 [redisson-netty-2-30] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for 127.0.0.1/127.0.0.1:6379
11:41:40.774 [redisson-netty-2-25] INFO org.redisson.connection.pool.SlaveConnectionPool - 24 connections initialized for 127.0.0.1/127.0.0.1:6379

This works fine:

Config config = new Config();
config.useMasterSlaveServers().setMasterAddress( "redis://127.0.0.1:6379").setReadMode( ReadMode.MASTER).setSubscriptionMode( SubscriptionMode.MASTER );
Redisson.create(config);

11:53:43.508 [redisson-netty-2-19] INFO org.redisson.connection.pool.MasterPubSubConnectionPool - 1 connections initialized for 127.0.0.1/127.0.0.1:6379
11:53:43.544 [redisson-netty-2-19] INFO org.redisson.connection.pool.MasterConnectionPool - 24 connections initialized for 127.0.0.1/127.0.0.1:6379

If useMasterSlaveServers is used, and there are no slaves I think it should behave the same as single server?
Also, I haven't looked yet, but not sure why 2 slave pools are created instead of 1.
Thanks!

**Comment by avcad** [comment]
@mrniko , I can report this as a new issue if you want

**Comment by mrniko** [comment]
@avcad 

It's a configuration issue. readMode = SLAVE by default. I'll add a check.

**Comment by avcad** [comment]
@mrniko , thanks! but is this also an issue?

When using master/slave with one slave, after the new commit are two slave pools instead of one.

Config config = new Config();
config.useMasterSlaveServers()
	.setMasterAddress( "redis://127.0.0.1:6379")
	.addSlaveAddress("redis://127.0.0.2:6379");
Redisson.create(config);
	
before
======
09:58:31.678 [redisson-netty-2-13] INFO org.redisson.connection.pool.MasterPubSubConnectionPool - 1 connections initialized for 127.0.0.1/127.0.0.1:6379
09:58:31.727 [redisson-netty-2-18] INFO org.redisson.connection.pool.MasterConnectionPool - 24 connections initialized for 127.0.0.1/127.0.0.1:6379
09:58:31.771 [redisson-netty-2-21] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for 127.0.0.2/127.0.0.2:6379
09:58:31.799 [redisson-netty-2-7]  INFO org.redisson.connection.pool.SlaveConnectionPool - 24 connections initialized for 127.0.0.2/127.0.0.2:6379

With latest code:
=================
10:02:34.671 [redisson-netty-2-24] INFO org.redisson.connection.pool.MasterPubSubConnectionPool - 1 connections initialized for 127.0.0.1/127.0.0.1:6379
10:02:34.675 [redisson-netty-2-25] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for 127.0.0.1/127.0.0.1:6379
10:02:34.728 [redisson-netty-2-32] INFO org.redisson.connection.pool.MasterConnectionPool - 24 connections initialized for 127.0.0.1/127.0.0.1:6379
10:02:34.732 [redisson-netty-2-4]  INFO org.redisson.connection.pool.SlaveConnectionPool - 24 connections initialized for 127.0.0.1/127.0.0.1:6379
10:02:34.760 [redisson-netty-2-3]  INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for 127.0.0.2/127.0.0.2:6379
10:02:34.787 [redisson-netty-2-25] INFO org.redisson.connection.pool.SlaveConnectionPool - 24 connections initialized for 127.0.0.2/127.0.0.2:6379

**Comment by mrniko** [comment]
@avcad 

Fixed
