### ISSUE TITLE
ErrorsLoggingHandler Exception occured. Channel

### ISSUE THREAD

**Issue by ftqiao** [redisson/redisson#4440]
![image](https://user-images.githubusercontent.com/6847901/180678978-b7eda9a3-5bf2-4530-82b2-3785cbd080d7.png)
micro service application with springboot but only redission(3.17.3) client.  applyed in k8s cluster, redis version 3.2.8.
this problem occasionally happend in 3.15.3 , too.

**Comment by mrniko** [comment]
I need full stacktrace

**Comment by ftqiao** [comment]
![image](https://user-images.githubusercontent.com/6847901/186076106-8a1999da-c769-4741-ae7f-381394fee66a.png)

**Comment by mrniko** [comment]
Is there any way to reproduce it?

**Comment by avcad** [comment]
@mrniko ,
The title of the commit is "PingConnectionHandler should close channel on..."
but it seems the code is doing the opposite?
 if (!(cause instanceof RedisLoadingException.....

I also noticed this message is probably misleading, because it shows the ping connection interval, not the ping timeout:
log.debug("channel: {} closed due to PING response timeout set in {} ms", ctx.channel(), config.getPingConnectionInterval());

**Comment by mrniko** [comment]
@avcad 

Some exceptions should be skipped. I'll fix the message. Thanks for pointing out.
