### ISSUE TITLE
Add Spring session integration

### ISSUE THREAD

**Issue by mrniko** [redisson/redisson#452]

**Comment by ziadloo** [comment]
My knowledge in this area is absolutely limited but I guess adding Spring Session integration is pointless. My original proposition to use Redisson as a session manager was due to the lack of distributed locks within Spring Session. This shortcoming is a result of being bounded to HttpSession's interface and the fact that it doesn't provide any APIs to lock the session. If Redisson is going to act under the same interface of HttpSession, it adds no value to the original Spring Session + Clustered Redis implementation!

As I said at the beginning of my comment, I'm not an expert but if this is really the case, I think the true value to the Redisson is the fact that it supports distributed locks. And this functionality can not be delivered through HttpSession's interface.

And just for the record, locking the whole session for some user is not really useful. The true value is in locking session entries one by one. Locking the whole session as one slows the overall responding by a great deal and is impractical.

**Comment by mrniko** [comment]
Done
