### ISSUE TITLE
Will redisson add support for Client-side caching ?

### ISSUE THREAD

**Issue by HuiWang1995** [redisson/redisson#4837]
Will redisson add support for Client-side caching that drafted by redis.io in 6.0 ?

**Comment by mrniko** [comment]
Client side caching is already supported with RLocalCachedMap object and available for all Redis versions. Since RESP3 doesn't gurantee local cache consistency if map instance was disconnected from Redis. Redisson has special option for this case reconnectionStrategy = org.redisson.api.LocalCachedMapOptions.ReconnectionStrategy#LOAD

**Comment by mrniko** [comment]
You can specify org.redisson.api.LocalCachedMapOptions.ReconnectionStrategy = CLEAR in this case. It does the same
