### ISSUE TITLE
session not found when the request goes to another pod

### ISSUE THREAD

**Issue by pavitramohan** [redisson/redisson#4875]
we are using "Azure Cache for Redis" service and deployed our webapplication in kubernetes using multiple pods. we still use some legay struts 1.1 based web 1.0 screens. we expected the web1.0 components to work seamlessly when we intrdcuced redis cache and libraries. It works some times but some times we see session not found exceptions when the request lands to another pod. Can you let us know what could we change to have better user experience.. our configuration in tomcat is as follows..

{
  "singleServerConfig": {
    "idleConnectionTimeout": 10000,
    "connectTimeout": 10000,
    "timeout": 3000,
    "retryAttempts": 3,
    "retryInterval": 1500,
    "password": "${rddpwd}",
    "subscriptionsPerConnection": 5,
    "clientName": null,
    "address": "rediss://${rddhost}:${rddport}",
    "subscriptionConnectionMinimumIdleSize": 1,
    "subscriptionConnectionPoolSize": 50,
    "connectionMinimumIdleSize": 10,
    "connectionPoolSize": 64,
    "database": 0,
    "dnsMonitoringInterval": 5000
  },
  "threads": 32,
  "nettyThreads": 64,
  "codec": {
    "class": "org.redisson.codec.SerializationCodec"
  }
}

**Comment by mrniko** [comment]
Did you try to set broadcastSessionEvents = true?

**Comment by pavitramohan** [comment]
our context.xml configuration is as follows. we did not set the "broadcastSessionEvents" ..which is true by default right ?
```xml
<Manager className="org.redisson.tomcat.RedissonSessionManager"
             configPath="${catalina.home}/conf/redisson.conf" readMode="MEMORY" updateMode="AFTER_REQUEST" keyPrefix="abc"/>
```

**Comment by mrniko** [comment]
> It works some times but some times we see session not found exceptions when the request lands to another pod.

It might be caused by replication lag. You need to set readMode=MASTER

**Comment by pavitramohan** [comment]
Still it did not work for us.. it still gives same exceptions..   I guess you meant readMode=MEMORY right.. readMode=Master does not exist..

**Comment by mrniko** [comment]
sorry, I meant readMode=REDIS

**Comment by nguyenahn** [comment]
We tried all options (readMode=REDIS, updateMode=DEFAULT), (readMode=REDIS, updateMode=AFTER_REQUEST), (readMode=MEMORY, updateMode=DEFAULT), (readMode=MEMORY, updateMode=AFTER_REQUEST) and also upgraded our Azure Cache for Redis to the latest version 6.0 and we still have the same issue.

Any suggestions that we can try.

Thank you.

**Comment by devondragon** [comment]
@nguyenahn Did you have any luck getting this working?  We seem to be facing a similar issue.

**Comment by nguyenahn** [comment]
@devondragon No I have not been able to get this working and still troubleshoot the issue.

**Comment by devondragon** [comment]
@nguyenahn We seem to have it working, although it's not ideal as it doesn't use any read replicas.  

in the tomcat context.xml we have readMode=REDIS, updateMode=DEFAULT, broadcastSessionEvents=true, broadcastSessionUpdates=false.

Then in the redission.yml file we have readMode=MASTER, subscriptionMode=MASTER, and since we're using a cluster, we set the nodeAddresses to just point to the config endpoint.

That seems to work for us, but it puts ALL the traffic on the MASTER nodes of the cluster, which isn't ideal.  Any other configs did not work consistently for us.

**Comment by nguyenahn** [comment]
@devondragon 
I tried in the tomcat context.xml as you recommended readMode=REDIS, updateMode=DEFAULT, broadcastSessionEvents=true, broadcastSessionUpdates=false and in our redisson configuration we tried both clusterServersConfig and replicatedServersConfig.
It looks like replicatedServersConfig is the correct config for us since we use Azure Redis Cache with cluster size 2 (Shard count 2) and we only have one end point for nodeAddresses. However, we have the error with MOVED redirection to the same end point
 "org.redisson.client.RedisException: MOVED redirection loop detected. Node rediss://x.x.x.x:yyyyy has further redirect to rediss://x.x.x.x:yyyyy"

Do you know why we had the MOVED redirection loop error?

**Comment by devondragon** [comment]
@nguyenahn Sorry to hear that.  I don't know why you'd be getting that.  I haven't seen that, and I haven't used Azure myself.

**Comment by mrniko** [comment]
@nguyenahn

`replicatedServersConfig` isn't compatible with Cluster setup and can't be used for Azure Redis Cache in cluster mode. You need to use ClusterServersConfig instead https://github.com/redisson/redisson/wiki/2.-Configuration/#24-cluster-mode

**Comment by nguyenahn** [comment]
@mrniko 
We tried clusterServersConfig as well, but in our Azure Cache for Redis, we have only one node address and one port number for cluster size > 1 and this caused the MOVED redirection loop detected exception because the node address redirected to itself.

Any ideas how we can have a correct configuration?

Thanks.

**Comment by mrniko** [comment]
@nguyenahn 

Can you share the logs in `trace` logging level for `org.redisson` package since application start till the moment of this redirect?

**Comment by nguyenahn** [comment]
@mrniko 

We tried with masterSlaveServersConfig and here are the errors:

17-May-2023 23:34:56.926 SEVERE [redisson-3-2] org.redisson.tomcat.RedissonSessionManager$2.onMessage Unable to handle topic message
        org.redisson.client.RedisException: MOVED redirection loop detected. Node rediss://xx.xxx.xxx.xxxx:yyyyy has further redirect to rediss://xx.xxx.xxx.xxx:yyyyy
                at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:492)
                at org.redisson.command.RedisExecutor.lambda$execute$5(RedisExecutor.java:195)

 2023-05-17T23:34:57,366+00:00  ERROR   https-jsse-nio-8443-exec-7                      - ServletException in '/jaffa/jsp/tiles/MainLayout.jsp': MOVED redirection loop detected. Node rediss$
 org.apache.jasper.JasperException: org.redisson.client.RedisException: MOVED redirection loop detected. Node rediss://xx.xxx.xxx.xxx:yyyyy has further redirect to rediss://xx.xxx.xxx.xxx:1$
        at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:589)

17-May-2023 23:34:57.374 WARNING [https-jsse-nio-8443-exec-7] org.apache.catalina.connector.Request.recycleSessionInfo Exception triggered ending access to session while recycling request
        org.redisson.client.RedisException: MOVED redirection loop detected. Node rediss://xx.xxx.xxx.xxx:yyyyy has further redirect to rediss://xx.xxx.xx.xxxx:yyyyy
                at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:492)
                at org.redisson.command.RedisExecutor.lambda$execute$5(RedisExecutor.java:195)

**Comment by nguyenahn** [comment]
@mrniko 
Do you know where I can get a document for Redisson PRO?
How do I get a Redisson PRO copy to try and see if it works with our application?

**Comment by mrniko** [comment]
Can you share the logs in trace logging level for org.redisson package **since application start till the moment of this redirect**?
