### ISSUE TITLE
Can there be an option to have Redisson only use daemon threads?

### ISSUE THREAD

**Issue by chaimmintz** [redisson/redisson#4914]
Right now Redisson uses some non-daemon threads, and apps must call `client.shutdown()` before main completes, otherwise the process won't actually terminate. Would it be possible to have a config option to relax that requirement and have Redisson only use daemon threads instead? I understand that means that the app won't have a chance to complete any work that the background threads are doing, but that is ok for our use case. The use case is that we have a library that uses Redisson to connect to Redis and clients of the library always forget to `close()` on the java client we give them, or it is created deep inside some object heirarchy or through dependency injection and it isn't straightforward to call `close()` before `main` returns, and as a result apps hangs on shutdown.

Our library either only reads data from Redis, or writes data that we are ok losing if the app were to shutdown before it gets flushed. I am assuming that abrupt shutdown won't leave Redis itself in a bad state (right now there are cases our user's apps are shutdown with SIGTERM and therefore `shutdown()` isn't called and we haven't seen any issues with redis as a result). If we can have this option to turn on a mode where Redisson only use daemon threads it will make its usage much more straightforward.

**Comment by mrniko** [comment]
I think this can be configured with proper executors.

**Comment by chaimmintz** [comment]
How does one configure the thread pools to use for redisson?

**Comment by tucu00** [comment]
I'm running into the same problem even after configuring the client to use an Executor that uses daemon threads.

` Config   config.setExecutor(Executors.newFixedThreadPool(threads, new DefaultThreadFactory("redissonx", true)));`

Even after this the client is stopping the JVM to end because of the 'redisson-timer' thread which is not a daemon thread.

I couldn't find a way to configure the timer so it uses a daemon thread.

Any suggestion?

Thanks
