### ISSUE TITLE
RedisClientConfig & Redisson Config from environment

### ISSUE THREAD

**Issue by cortlepp** [redisson/redisson#5251]
I am trying to integrate a redis cache into an existing Java application and I am struggling with the configuration of the RedisClient. 
I want the redis client to be configurable via p.e. environment variables. 

In the `Config` class for the Redisson client I found the `fromYAML` methods which to probably suit my usecase very well, but I cannot find anything equivalent in `RedisClientConfig`. Also, why do I have to configure the low level client completely separate from the high level one? Or is there a way to get from one to the other that I have overlooked?

**Comment by mrniko** [comment]
low level client instances aren't exposed by Redisson. Can you use Redisson only?

**Comment by cortlepp-intershop** [comment]
Well, it would not be ideal. I want to use it to send `BGSAVE` commands in order to ensure consistency during some operations. If I leave that out and a master node crashes at the wrong point in time, my application will send out infomation which it has already evicted from the redis cache (after the crashed redis was restored from the outdated backup).

If it is not possible to do this we will probably just try whether our redis-deployment is stable enough and these issues don't appear in practice, but I'd prefer erring on the side of caution.

**Comment by mrniko** [comment]
I can expose the client through RedisNode.getClient() method.

Note: Add BGSAVE, LASTSAVE, SAVE commands.
