### ISSUE TITLE
request.changeSessionId does not change the session id in redis

### ISSUE THREAD

**Issue by bgorven** [redisson/redisson#5426]
This issue is similar to https://github.com/redisson/redisson/issues/1813, but affects redisson-tomcat.

**Expected behavior**

After changing the session id, attributes that were stored in the session should still be accessible.

**Actual behavior**

Session attributes are not copied or moved to the new session id.

**Steps to reproduce or test case**

any

**Redis version**

any

**Redisson version**

any

**Redisson configuration**

any

**Comment by KalpeshPatil02** [comment]
If you are experiencing issues with session attribute transfer, it's possible that session replication is not correctly set up. You should check that your Tomcat cluster has session replication enabled and properly configured. You can configure session replication in Tomcat by using <distributable/> in your web.xml and setting up the <Cluster/> element in your server.xml. Make sure that Redisson is properly integrated into this configuration.

**Comment by KalpeshPatil02** [comment]
is it helpful?

**Comment by jlaudadio** [comment]
@KalpeshPatil02 I'm not sure what this has to do with cluster configuration.  I'm seeing this behavior on a non-clustered Tomcat instance with Redis.  When changeSessionId() is called, what's supposed to happen is the session id changes from A to B but the contents of the session are not supposed to change.  What seems to happen with RedissonSessionManager is that the Redis hash key by A is deleted and then a new hash is written for B.  The contents of the hash need to be copied over before hash A is deleted.

**Comment by jlaudadio** [comment]
Looking into this a bit further, this seems only to be a problem in read mode `REDIS`.  I'm not terribly familiar with the `RedissonSessionManager` source, but here's my read on what's going wrong after debugging this for a couple of hours...

The way Tomcat's `ManagerBase::changeSessionId()` (which RedissionSessionManager extends) works is by generating a new id and then calling `setId(newId)` on the
existing (Radisson) session object instance.  `setId()` is implemented in Tomcat's `StandardSession` which `RedissonSession` extends. The `setId()` implementation first tells the session manager to remove it (`manager.remove(this)` where `this` = the current `RedissonSession` instance). `RedissonSessionManager::remove(session)` calls `RedissonSession::delete()` which removes the session's hash from Redis and sets `RedissonSession::map` to `null`. 

Now we come back `StandardSession::setId()` which sets `session.id` to the `newId` and then calls `RedissonSessionManager::add(this)` where `this` = the same current session object.  
`RedissionSessionManager` calls `RedissonSession::save()` which tries to retrieve the hash from Redis, but since it's a new session id it's not there so `RedissonSession::map` is initialized to an empty map. 

Now, depending on the `readMode` option, here is how we end up recovering from the lost session data or not.  At this point, `RedissonSession::attr` map still contains all of the session attributes for the session.  If `readMode == MEMORY`, then `RedissonSession::save()` puts all of those attributes into `RedissonSession::map` before writing it back to Redis.  Otherwise, only attributes contained in `RedissonSession::updatedAttributes` (containing only attributes updated during this particular request) are put back into the map before saving the session (for the first time) to Redis, losing any attributes that weren't touched during the request.

So to fix this bug, it seems like you need to detect if the session id is being changed because of a session id rotation. In that case, all of the session attributes (not just ones written / read during the request) need to be carried over to the new session hash, either by reading all of the data out of Redis or by issuing a Redis `COPY` to put the hash into Redis under the new session key.

**Comment by mrniko** [comment]
Merged
