### ISSUE TITLE
Consider consolidating tests on Travis CI

### ISSUE THREAD

**Issue by BanzaiMan** [redisson/redisson#553]
Hello!

Thank you for using Travis CI for your testing needs.

We noticed, however, that currently this repository configures 180 jobs for each push. This puts undue burden on the system, not to mention long waits for each build to complete.

I have marked the user @mrniko as an offender to prevent further queueing of builds from this repository at this time.

I apologize for the inconvenience. Please send email to support@travis-ci.com when the jobs are sufficiently consolidated.

Thank you!

**Comment by mrniko** [comment]
@jackygurui What can we do in this situation?

**Comment by jackygurui** [comment]
@BanzaiMan First of all, apologise for causing problem on your infrastructure. 

I had to do it like this way with no other choice, because of inconsistent test result when running tests together. In general, I have met those problems, bare in mind all tests have passed locally: 1) Some tests could fail randomly and then re-run the job again they may pass but others have passed earlier could fail this time. 2) When running high concurrent test jobs, there is a great chance it may stuck for a few hours and been killed by watchdog from travis. 

I went a great length to make our tests compatible to travis, started from creating a flag called `travisEnv`. By setting it to true, which is set in .travis.yml file, it skips a few really high concurrent tests, it also forces the redis server to stop and start for each test job, because, by default, calling reset command on redis server could get stuck in travis.

Is there anything else you could suggest other than just consolidate the jobs? 

Much Appreciated!
