### ISSUE TITLE
Memory consumption is very high, possible memory leak with io.netty.channel.DefaultChannelHandlerContext

### ISSUE THREAD

**Issue by Natalia588** [redisson/redisson#5955]
Hello,

Our service uses Redisson client library to work with Azure Redis. Pods memory consumption is very high, it constantly grows. Heap dump analysis shows that io.netty.channel.DefaultChannelHandlerContext is suspected for memory leak, it is the top consumer. Could you please advise why this issue can be observed? Maybe there is something wrong with the config or anything else.

![image](https://github.com/redisson/redisson/assets/63799911/41ad3801-2835-4570-bb0c-8681088cd70e)

We are using the RMapCache structures. 

Thanks in advance.

**Comment by mrniko** [comment]
Can you share a memory dump?

**Comment by Natalia588** [comment]
> [mrniko](/mrniko)

Yes, please find it in the private repo here - https://github.com/Natalia588/data/releases/tag/heapdump
I've invited you to join it

**Comment by mrniko** [comment]
Thanks. Seems like it's a classloader leak

![image](https://github.com/redisson/redisson/assets/1104661/4c943c10-7a55-4664-a6c5-83c3e7292eed)

**Comment by Natalia588** [comment]
Many thanks. What would you recommend? Is it a Netty issue?

**Comment by mrniko** [comment]
18K classes. I don't think that they belong to Redisson or netty

**Comment by Natalia588** [comment]
Ok, thank you

**Comment by techwizardg** [comment]
@Natalia588  how did you solve this? We are facing the same issue

**Comment by mrniko** [comment]
@techwizardg 

Can you share the memory dump?

**Comment by techwizardg** [comment]
Issue Summary
 
We’re experiencing a memory leak when connecting to Redis/Valkey using the Redisson client 3.30.0.
 
Details
 
	•	Context: The application has 32 default Netty threads.
	•	Behavior: Memory usage continuously increases, eventually causing the application to be OOM killed. The application publishes to Redis/Valkey on specific events.
	•	Observations: This issue occurs only with Valkey and not with Redis.
	•	Diagnostics Attempted:
	•	Heap Dump Analysis: No conclusive information was found; only the Netty threads appeared to hold approximately 4MB each.
	•	System Properties Used: Tried adjusting Netty’s memory usage by setting:
 
-Dio.netty.noPreferDirect=true 

-Dio.netty.maxDirectMemory=0 

-Dio.netty.allocator.type=unpooled 

-Dio.netty.leakDetectionLevel=advanced
	•	Result: Despite these settings, memory still increases continuously over time.
 
Expected Behavior
 
The application should maintain stable memory usage over time without a continuous increase when connected to Valkey, similar to its behavior with Redis.
 
Additional Information
 
Any guidance on configurations or memory management specific to Redisson with Valkey would be appreciated.

**Comment by mrniko** [comment]
It's hard to find a cause without the memory dump.
