### ISSUE TITLE
（过期消息积压在RDelayedQueue）Expired messages are backlogged in RDelayedQueue, expired but not transferred to the expired queue

### ISSUE THREAD

**Issue by ying3885** [redisson/redisson#6020]
1.程序运行一段时间后，过期的消息就会停止向过期队列转移，原来大概能正常工作一天多的时间，现在也就1个小时左右，
After running the program for a period of time, expired messages will stop being transferred to the expiration queue. Originally, it could work normally for over a day, but now it only takes about an hour。

2.我的业务是消息30秒过期，全局用的一个RDelayedQueue对象，并且做了缓存，没有销毁
My business is message expiration in 30 seconds, using an RDelayedQueue object globally and caching it without destruction

3.消息存入后会有线程每秒从blockingDeque 中 poll 出一个已过期的消息进行处理
After the message is stored, a thread will poll an expired message from the blockingDeque every second for processing

4.经添加日志打印观察，日志正常走到了QueueTransferTask 中schedulerTopic 监听器的onMessage 方法，这个方法一直在收到消息，但是后续的pushTaskAsync 方法并没有执行
After adding and printing the logs, it was observed that the logs went smoothly to the onMessage method of the schedulerTopic listener in the QueueTransferTask. This method has been receiving messages, but the subsequent pushTaskAsync method has not been executed
![1](https://github.com/redisson/redisson/assets/173755256/370f28ff-3280-4b47-8308-d4c78fc80a40)
![2](https://github.com/redisson/redisson/assets/173755256/6fe42c16-c971-461a-9dca-a0100ccf576c)

5.我的环境这个问题现在必现，但是没有找到原因，请问有前辈知道是什么原因，以及解决方案吗
The problem with my environment is now inevitable, but the cause has not been found. Do any seniors know what the cause is and how to solve it

**Comment by TsukasaHwan** [comment]
你可以试试重新订阅一下队列redissonClient.getDelayedQueue(blockingDeque);

**Comment by iridescenceZz** [comment]
我也出现了同样的问题，服务运行一段时间后过期的消息就会停止向过期队列转移。查询了相关 key 的数据，redisson_delay_queue:{my_queue}、redisson_delay_queue_timeout:{my_queue}、均有数据，但是队列my_queue 是空。相关的消息已经到了过期时间。消费queue.take() 获取不到数据再等待。

**Comment by iridescenceZz** [comment]
我也出现了同样的问题，服务运行一段时间后过期的消息就会停止向过期队列转移。查询了相关 key 的数据，redisson_delay_queue:{my_queue}、redisson_delay_queue_timeout:{my_queue}、均有数据，但是队列my_queue 是空。相关的消息已经到了过期时间。消费queue.take() 获取不到数据。
I've encountered the same issue: after running for some time, expired messages stop being moved to the expiration queue. I checked the relevant data for keys redisson_delay_queue:{my_queue} and redisson_delay_queue_timeout:{my_queue}, both of which contain data. However, the queue my_queue is empty. The related messages have already reached their expiration times. When I try to consume using queue.take(), it does not return any data.


redisson version:3.25.0

config：
<img width="925" alt="image" src="https://github.com/user-attachments/assets/4b44e863-4e4a-4b1f-9c98-9bf5bac53bf5">

**Comment by Guohua-Wang** [comment]
建议提交问题附带环境/版本能帮助其它开发者高效地复现问题和解决问题.
-☑可能的解决方案:升级你的 Redis 版本到Redis 7.2.6
-我的复现环境: Redis 5.0.10,<redisson.version>3.34.1</redisson.version>,

复现问题现象:
延时消息无法到达目标消费队列,而是滞留(堆积)在两个中间集合中.更具体的:程序启动时生产者向myDelay发送延时消息,这时能够正常生产和消费,经过长时间静默后(不生产也不消费),这样再次向myDelay发送延时消息,这时会发生滞留(堆积),原本按延时时间应该就绪而被消费的延时消息都堆积到ZSet"redisson_delay_queue_timeout:{myDelay}"和List"redisson_delay_queue:{myDelay}"中,一直不会发往myDelay而被消费.

It is highly recommended that submitting issues with an environment/version can help other developers reproduce and resolve issues efficiently.
- Possible solution: Upgrade your Redis version to Redis 7.2.6
- My recurring environment: Redis 5.0.10,<redisson.version>3.34.1</redisson.version>,

Recurring problem symptoms:
Delayed messages do not reach the target consumption queue, but instead are stuck (stacked) in two intermediate sets. More specifically: when the program starts, the producer sends a delay message to myDelay, then it can produce and consume normally, after a long time of silence (neither production nor consumption), so that the delay message is sent to myDelay again, then the delay message will occur (pile), and the delay message that should be ready according to the delay time and be consumed will be piled into ZSet"redisson_delay_queue_timeout:{myDelay}" and List"redisson_delay_queue:{myDelay}", causing it to be consumed without being sent to myDelay.
