### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by lrn2prgrm** [redisson/redisson#749]
I need to compare what is the performance of RCache vs RMap or redisson vs other libraries. Could you provide benchmarks?

This is more of a suggestion than an issue per se.

**Comment by mrniko** [comment]
Hi!

Currently, I'm working on it. I'll publish performance comparison of two Redisson editions: Open-source vs PRO.

**Comment by jackygurui** [comment]
Since there is no RCache I assume you are asking us to compare the performance RMap against other types of Cache implementations that Redisson provides such as RMapCache, SpringCache and JCache. I think it is quite obvious that RMap is going to out perform the others. It is simply because the Caching system itself is a lot more complex than a simple Map structure. 

As to compare Redisson with other libraries, I am not sure if it is comparable to be honest. It is like compare apples with oranges. 

Redisson is a "higher level" library compared to other Redis clients, it offers much more than just a way of executing a Redis command like any others. If offers an abstraction to hide Redis, as a separation of concern, if you like, that when you architecting your application, you don't have to stop and think which Redis command is equivalent to `putIfAbsent` in Java. People choose Redisson won't because it can execute the `hset` command faster than other clients, although I am not saying it can't.

As to compare Redisson with other in-memory data grid solutions, it is another story on its own. Redisson is different to other solutions simply because others tend to provide the client and storage together, such as HazelCast, GridGain and Coherence, whereas Redisson is a client side library that's working with your exising Redis NoSQL server. So strictly speaking it is not comparable.

**Comment by mrniko** [comment]
Here is the [Benchmark whitepaper](https://redisson.pro/Redisson%20PRO%20benchmark%20whitepaper.pdf). It provides performance charts for both RMap and RMapCache objects.

**Comment by ALSowjanya** [comment]
@mrniko benchmarks mentioned in the above comment is with 6bytes of size. Do you have benchmarks with higher size like 50KB 1MB.

**Comment by mrniko** [comment]
@ALSowjanya 

I'm afraid no.
