### ISSUE TITLE
Feature like EntryProcessor

### ISSUE THREAD

**Issue by Flo354** [redisson/redisson#910]
Would it be possible in the future to have a feature which can get entries matching a Predicate?
For example, if I have an RMap<String, MyObject>

```java
class MyObject {
   public String a;
   ...
}
```

With an EntryProcessor i could have the ability to get all MyObject in the map that match **a == "hello"** for instance.

**Comment by jackygurui** [comment]
This is a typical "Search by value" scenario which is always a shortfall for any kind of KV stores. 

Typically you are expected to maintain some kind of secondary index where the lookup can be faster than going through all entries. 

If you do want to go through all the entries, there is an iterator provided for a RMap that can let you perform such look up. Internally a map iterator is using the HSCAN for the job. The only thing is it doesn't do server side field pattern matching because the codec is controlled on the client side. 

Another thing you can do is use MapReduce function.

**Comment by jackygurui** [comment]
MapReduce is introduced to cover this kind of usage and the pattern matching process can be executed in parallel. Adding parallelism to this type of problem can speed up the process by a lot.

Will discuss with @mrniko and see if we can have a EntryProcessor based on MapReduce.

**Comment by Flo354** [comment]
Thanks for your answer

I just read the [wiki for MapReduce](https://github.com/redisson/redisson/wiki/9.-distributed-services#95-distributed-mapreduce-service), and I don't understand very well.

Could you provide a snippet showing how I can do a search by value scenario. Of course, I know that there will be performances impact since there is no secondary index on this entry.

I think that if you develop an EntryProcessor, you will have to develop a feature to define secondary indexes. Otherwise it will be useless for very big map (in my case: more than 1M entries).

**Comment by mrniko** [comment]
Use search engine for Live objects https://github.com/redisson/redisson/wiki/9.-distributed-services#923-search-by-object-properties
