### ISSUE TITLE
Live Object service have issues while working with inherited classes

### ISSUE THREAD

**Issue by 13kunal** [redisson/redisson#930]
So i have the following use-case : 

```
@REntity
class Child extend Parent{
 Child(String id){
     super(id);
 }
}

```
```
class Parent { 
  @RId
  String id;
  Parent(String id){
     this.id = id;
  }
}
```
And when i make Child object as my live object as Follows : 
```

Child child = new Child("1");
child = rLiveObjectService.merge(child);
```
I get the following error -- 

         java.lang.IllegalStateException: size = 0
	at net.bytebuddy.matcher.FilterableList$AbstractBase.getOnly(FilterableList.java:108)
	at org.redisson.RedissonLiveObjectService.getRIdFieldName(RedissonLiveObjectService.java:537)
	at org.redisson.RedissonLiveObjectService.persist(RedissonLiveObjectService.java:163)
	at org.redisson.RedissonLiveObjectService.merge(RedissonLiveObjectService.java:153)

**Comment by sdjacobs** [comment]
+1

**Comment by jackygurui** [comment]
the error happens when there is no get method for the `@RId` field

**Comment by sdjacobs** [comment]
I don't think so. I tried this example as written, added `getId()` methods, and I got the same error.

I'm fairly sure that if you call `RLiveObjectService.persist` on an object of type Child, since the `@RId` field is defined in its supertype, Redisson won't be able to find it. This is because [`Introspectior.getFieldsWithAnnotation()`](https://github.com/redisson/redisson/blob/8500d4d0023b1c334fa032c5c9d9790a7b587724/redisson/src/main/java/org/redisson/liveobject/misc/Introspectior.java#L63) will only return fields declared in Child - not any fields declared in Parent.

Being able to make LiveObjects from subclasses of a single class defined as an `@REntity` would be a great feature for Redisson - at least for me!

**Comment by jackygurui** [comment]
@sdjacobs You're absolutely right. Do you think you can send us a PR for this?

**Comment by sdjacobs** [comment]
I can give it a shot

**Comment by jackygurui** [comment]
@sdjacobs Thank you!
