### ISSUE TITLE
how to use redLock in cluster

### ISSUE THREAD

**Issue by yangdailin** [redisson/redisson#956]
I have build the cluster of redis, 3 master, 3 slave. According to the Redlock algorithm: 'It tries to acquire the lock in all the N instances sequentially, using the same key name and random value in all the instances'.'
i think every lock name is must same, it's right?the following is my example, this is right?
Config config = new Config();
config.useClusterServers().addNodeAddress("redis://xxx:7000", "redis://xxxx:7001","redis://xxx:7002", "redis://xxxx:7003","redis://xxx:7004", "redis://xxxx:7005");
RedissonClient redisson1 = Redisson.create(config);
RedissonClient redisson2 = Redisson.create(config);
RedissonClient redisson3 = Redisson.create(config);
RedissonClient redisson4 = Redisson.create(config);
RedissonClient redisson5 = Redisson.create(config);
RedissonClient redisson6 = Redisson.create(config);
String lockName = "test";
RLock lock1 = redisson1 .getLock(lockName);
RLock lock2 = redisson2 .getLock(lockName);
RLock lock3 = redisson3 .getLock(lockName);
RLock lock4 = redisson4 .getLock(lockName);
RLock lock5 = redisson5.getLock(lockName);
RLock lock6 = redisson5.getLock(lockName);
RedissonRedLock lock = new RedissonRedLock(lock1, lock2, lock3, lock4, lock5, lock6);
Thanks!

**Comment by mrniko** [comment]
You shouldn't create 6 Redisson instances in case of cluster usage, just instantiate a single one.
If you want to create 6 locks in cluster you should use a different name for each of them. Something like this:

```java
Config config = new Config();
config.useClusterServers().addNodeAddress("redis://xxx:7000", "redis://xxxx:7001","redis://xxx:7002", "redis://xxxx:7003","redis://xxx:7004", "redis://xxxx:7005");
RedissonClient redisson = Redisson.create(config);
RLock lock1 = redisson.getLock(lockName + "1");
RLock lock2 = redisson.getLock(lockName + "2");
RLock lock3 = redisson.getLock(lockName + "3");
RLock lock4 = redisson.getLock(lockName + "4");
RLock lock5 = redisson.getLock(lockName + "5");
RLock lock6 = redisson.getLock(lockName + "6");
RedissonRedLock lock = new RedissonRedLock(lock1, lock2, lock3, lock4, lock5, lock6);
```

Keep in mind if you need to bind lock to each of cluster master node you need to specify correct name bounded to corresponding cluster node.

**Comment by yangdailin** [comment]
I try it, it's ok! thanks, but i can't understand you said that 'if you need to bind lock to each of cluster master node then you should specify correct name bounded to corresponding cluster node.',  how to specify correct name bounded to corresponding cluster node, can you give me an example? thanks

**Comment by mrniko** [comment]
>  how to specify correct name bounded to corresponding cluster node? can you give me an example? thanks

It's a tricky part, to do this you need generate a name which valid for slots. Maybe in brute-force way.
For example, we have 3 master nodes in cluster:
1 node has slots [1, 5000]
2 node has slots [5001, 10000]
3 node has slots [10001, 16834]

to fit on 1 node, name should bind to slots between [1, 5000], for example: name89232,
to fit on 2 node, name should bind to slots between [5001, 10000], for example: name38945,
to fit on 3 node, name should bind to slots between [10001, 16834], for example: name01923,

Slots calculation for object's name explained [here](https://redis.io/topics/cluster-spec#overview-of-redis-cluster-main-components). 

> 'It tries to acquire the lock in all the N instances sequentially, using the same key name and random value in all the instances'.' your example seem not same key name, why?

It's not possible to use same name on different cluster nodes due to difference in slot numbers each of them has. You'll get an error in this case.

**Comment by yangdailin** [comment]
thanks very much. I read this algorithm description again. in your case, the 'using the same key name and random value in all the instances' refer redisson.getLock(lockName + "1"), it is right?

**Comment by mrniko** [comment]
right, but "1", "2"... suffixes are provided just for clarity. In practice you need to use "real" value

**Comment by yangdailin** [comment]
ok, thanks

**Comment by childewuque** [comment]
In practice，sometimes if the key is a special lock key ，we  will get the 3 locks from one same master。
Because  CRC16(KEY) MOD 16384  is not  regular  according to the full key name，e.g. the biz key is ""iBePL"

**Comment by childewuque** [comment]
I'm wondering about it

**Comment by lgxbslgx** [comment]
> in your case, the 'using the same key name and random value in all the instances' refers redisson.getLock(lockName + "1"), key means 'lockName' and random value means '1', it is right?

@mrniko @yangdailin I don't think it is right. In my opinion, the key means `lockName + "1"`, and the random value is automatically generated by `redisson`.  The fellow code which is in the `RedissonLock` generates the random value.
```Java
protected String getLockName(long threadId) {
    return id + ":" + threadId;
}
```

And maybe  it is impossible to use redlock in a cluster. Because the Redlock algorithm declares the precondition. As shown below.
> In the distributed version of the algorithm we assume we have N Redis masters. Those nodes are totally independent, so we don’t use replication or any other implicit coordination system.

The notes in a cluster is not totally independent so that it is impossible to use Redlock.

The implement of the Redlock in `redisson` could be viewed as a variant of the algorithm. It uses different keys in a cluster in replace of `the same key in all the instances`. But I think the variant might not be exactly equal to the Redlock.

On the one hand, we can't get the key bounded to corresponding cluster node easily.
On the other hand, we can't prove that they are equal in theory.

If we already have the redis cluster, it is wasteful to create additional and independent redis notes just for the Redlock.
@antirez do you have any good ideas for using Redlock in cluster. Should we use another algorithm to implement distributed locks in cluster? We need your help.

**Comment by mrniko** [comment]
@lgxbslgx 

Redisson's RedLock allows to use RLock objects belong to different Redisson client hence which could be connected to different Redis setup.

**Comment by lgxbslgx** [comment]
@mrniko thank you for your reply.
So it means we have to use independent redis nodes instead of cluster and the way [you described above](https://github.com/redisson/redisson/issues/956#issuecomment-314396685)  is not enough to implement Redlock. Am I right?

**Comment by mrniko** [comment]
@lgxbslgx 

Yes, if we're talking about independent nodes.

**Comment by lgxbslgx** [comment]
@mrniko ok, thanks.

**Comment by DarrenJiang1990** [comment]
so，redisson don't  implement the redlock algorithm

**Comment by mrniko** [comment]
@DarrenJiang1990 

It does but you need to locate locks manually.

**Comment by anatolysergeev** [comment]
Hello
Ok, I understand how to lock master nodes in cluster, but I don't understand how to lock slave nodes in cluster manually?
According to the Redlock algorithm we should lock all the instances sequentially, shouldn't we?

**Comment by mrniko** [comment]
I think masters nodes are enough. Since you always write on master

**Comment by Hunter-Chen** [comment]
> so，redisson didn't implement the redlock algorithm

Not 100% implementaion, since the Redlock definition says "It tries to acquire the lock in all the N instances sequentially, **using the same key name** and random value in all the instances"

Also, it says "In the distributed version of the algorithm we assume we have N Redis masters. _Those nodes are totally independent_,"

But still, we can consider RedissonRedLock a redlock implemention.
