### ISSUE TITLE
why not poll a RedisConnection directly without using connectionFuture

### ISSUE THREAD

**Issue by q6413260** [redisson/redisson#966]
in class CommandAsyncService 498-503 line
        final RFuture<RedisConnection> connectionFuture;
        if (readOnlyMode) {
            connectionFuture = connectionManager.connectionReadOp(source, command);
        } else {
            connectionFuture = connectionManager.connectionWriteOp(source, command);
       }
In my opinion, after the bootstrap(RedissonClient redisson = Redisson.create(config)),we have 
Created serveral long connections  from the client to redis server. 
Can we poll the connection from che ClientConnectionsEntry.freeSubscribeConnections  directly
without using the connectionFuture. I think using che connectionFuture is nonecessary。
Who can answer the question？Thanks

**Comment by q6413260** [comment]
And by the way, 
RFuture<RedisConnection> connectionFuture connectionFuture = connectionManager.connectionWriteOp()
RedisConnection connection = connFuture.getNow();
won't send reqeust to the redis server in fact.

**Comment by jackygurui** [comment]
In your code:
```
RFuture connectionFuture connectionFuture = connectionManager.connectionWriteOp()
RedisConnection connection = connFuture.getNow();
```
`getNow` doesn't guarantee the future would be completed. It will return you null when it is still in progress. So it is a bit pointless to call `getNow` at that stage. May be you were trying to suggest `get` method? The problem is `get` method is a blocking method and that would defeats the purpose of writing a method that tries to perform async actions i.e. non-blocking.

**Comment by q6413260** [comment]
thanks
