### ISSUE TITLE
Redisson Connect to Cluster via DNS

### ISSUE THREAD

**Issue by akshaymani** [redisson/redisson#993]
It will be nice to have a functionality to connect via redisson to redis using a DNS as hostname instead of specifying host:port of all the nodes.

**Comment by mrniko** [comment]
Could you please describe your case and maybe suggest how API should looks like?

**Comment by akshaymani** [comment]
I am already using JedisCluster and Jedis (jedis 2.9.0) in my applications but for the async capabilities provided by Redisson want to switch to it.

I am using AWS ElasticCache Provided Redis Cluster with Multi-AZ mode with Automatic Failover enabled and want to hide the nodes being used so that the Operations team can add / remove nodes without having to check with the developers - we are using below given code for connecting. As you can see JedisCluster is able to auto-detect all the nodes operating underneath so if any slave is promoted to master then developers don't need to do any special handling for it. While as per the docs specified for Redisson we need to specify all the nodes explicitly, so any change in nodes structure requires a deployment in production environment. 

String hostName = properties.getProperty("hostname", "redis-cluster.orgname.net");
Integer port = Integer.parseInt(properties.getProperty("port", "6379"));
HostAndPort hostAndPort = new HostAndPort(hostName, port);
Set<HostAndPort> nodes = new HashSet<HostAndPort>();

GenericObjectPoolConfig poolConfig = new GenericObjectPoolConfig();
poolConfig.setMaxTotal(Integer.parseInt(properties.getProperty("max_total", "100")));
poolConfig.setMaxIdle(Integer.parseInt(properties.getProperty("max_idle", "5")));
poolConfig.setBlockWhenExhausted(Boolean.parseBoolean(properties.getProperty("block_when_exhausted", "false")));

JedisCluster redisCluster = new JedisCluster(nodes, poolConfig);

And, just a suggestion in redisson instead of using "rediss://" for SSL connection and changing host / port config per node it will be better if another method is exposed similar to setSSLModeEnabled(boolean flag) since SSL connection required or not I guess will not vary across the nodes.

**Comment by mrniko** [comment]
> While as per the docs specified for Redisson we need to specify all the nodes explicitly, so any change in nodes structure requires a deployment in production environment

No. Using Redisson Cluster you shouldn't specify all nodes. It requires only one cluster node to work.

**Comment by akshaymani** [comment]
If the max no of connections to redis configured in redisson client is lets say 200 and no of current connections is also 200 and there is a new request that comes to my application that will try to connect via redisson then either it can wait for connection to become available or it can say proceed ahead since connections are exhausted - for that block when exhausted configuration is there - how do we configure that via redisson ?
And, when you say just one cluster node to work then you mean one node per shard or any one node in the cluster ?

**Comment by akshaymani** [comment]
@mrniko i tried by giving only the master nodes in the address and it is able to detect the slaves as well. So, the only pending query is how is the block when exhausted configuration handled in redisson ?

**Comment by slolo83** [comment]
@akshaymani I have been reading your issue and I have maybe some questions for you.
@mrniko Tell me if this is not appropriate to this issue but it seems to me good to put it there.

I'm also using AWS elasticache redis cluster (Cluster Mode enabled) with Multi-AZ mode with Automatic Failover enabled in 3.2.4.

Are you using the same configuration ? 

So I'm using in my application only the configuration endpoint like below 

`Config config = new Config();`
`ClusterServersConfig clusterServersConfig = config.useClusterServers()`
`.setScanInterval(1000)`
`.setReadMode(ReadMode.MASTER_SLAVE);`
`.addNodeAddress("redis://serviceauthbis.coakwj.clustercfg.euw1.cache.amazonaws.com:6379");`
`.setConnectTimeout(1000)`
`.setIdleConnectionTimeout(1000)`
`.setReconnectionTimeout(1000)`
`.setRetryAttempts(1)`
And it discovers all the nodes.

But on AWS elastiCache, it's possible to simulate a fail over on the primary node of a shard.
In my test, I have only one shard containing one primary and one replica.

If I do simulate a fail over on the primary, it takes 7 minutes to redisson to connect to my replica. 
Why ? Because if I understood well, we can give one node (as I did) to the configuration and Redisson is able to discover other nodes (It actually did when I launched my app). So why does Redisson not switch directly to the replica after the command execution timeout error as you can see below, the error is at 08:34:37 and my redis cluster is only available here 08:41:35. Maybe this is a problem on AWS elastiCache but I try to understand why my cache is not available during 7 minutes when there is still one node working ?

`08:34:37.191  WARN 17529 o.r.c.p.SlaveConnectionPool              : host /10.196.84.112:6379 disconnected due to failedAttempts=3 limit reached`
`08:34:42.107 ERROR 17529 o.r.c.ClusterConnectionManager           : Can't execute CLUSTER_NODES with /10.196.84.112:6379`

org.redisson.client.RedisTimeoutException: Command execution timeout for /10.196.84.112:6379
	at org.redisson.client.RedisConnection$2.run(RedisConnection.java:212) [redisson-3.5.0.jar:?]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-common-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120) [netty-common-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-common-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [netty-common-4.1.13.Final.jar:4.1.13.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

`08:35:32.396  INFO 17529 o.r.c.ClusterConnectionManager           : changing master from redis://10.196.84.112:6379 to redis://10.196.17.70:6379 for 0`
`08:35:32.423  INFO 17529 o.r.c.ClusterConnectionManager           : slave redis://10.196.17.70:6379 removed for slot ranges: [[0-16383]]`
`08:35:35.439  INFO 17529 o.r.c.p.MasterConnectionPool             : 10 connections initialized for /10.196.17.70:6379`
`08:40:05.504  INFO 17529 o.r.c.p.SlaveConnectionPool              : 10 connections initialized for /10.196.84.112:6379`
`08:40:05.505  INFO 17529 o.r.c.p.SlaveConnectionPool              : host /10.196.84.112:6379 successfully reconnected`
`08:41:35.682  INFO 17529 o.r.c.ClusterConnectionManager           : slave: redis://10.196.84.112:6379 added for slot ranges: [[0-16383]]`

@akshaymani Did you experiment the same issue ?

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/issues/993#issue-246272843

Done in https://github.com/redisson/redisson/issues/1213
